# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='custom_pricing',
            field=models.BooleanField(default=False, verbose_name='Preço customizado'),
        ),
        migrations.AddField(
            model_name='plan',
            name='custom_pricing_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição para preço customizado'),
        ),
    ]
