# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-11 19:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_auto_20181213_1722'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0003_charge_chargeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('card_name', models.CharField(max_length=255, verbose_name='Nome no cartão')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('cpf_cnpj', models.CharField(max_length=255, verbose_name='CPF/CNPJ')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefone')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billingdetails_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Address', verbose_name='Endereço de cobrança')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billingdetails_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billingdetails_office', to='core.Office', verbose_name='Escritório')),
            ],
            options={
                'ordering': ['office', 'card_name'],
            },
        ),
    ]
