# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20190621_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='card_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome no cartão'),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CPF/CNPJ'),
        ),
    ]
