version: "3"

services:
  web:
    volumes:
      - .:/app
      - web-static:/app/staticfiles
      - web-media:/app/media
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    depends_on:
      - db
  nginx:
    image: nginx:1.13
    volumes:
      - ./containers/nginx/conf.d/ezl.conf:/etc/nginx/conf.d/default.conf
      - web-static:/usr/share/nginx/html/static
      - web-media:/usr/share/nginx/html/media
      - letsencrypt-www:/usr/share/nginx/html/certbot
      - letsencrypt-etc:/etc/letsencrypt
    depends_on:
      - web
  db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: ezl
      POSTGRES_USER: ezl
      POSTGRES_PASSWORD: ezl
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./containers/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
volumes:
  db-data:
  web-media:
  web-static:
  letsencrypt-www:
  letsencrypt-etc: