version: "3"

services:
  builder:
    build:
      context: .
      dockerfile: containers/web/Dockerfile
      args:
        requirements_file: development.txt
    image: ezl:latest
    command: date
    environment:
      ENV: development

  web:
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      ENV: development
    ports:
      - "8000:8000"
    depends_on:
      - builder
      - db
      - tunnel
      - queues
  ws:
    image: ezl:latest
    volumes:
      - .:/app
      - ezl-logs:/var/log/ezl
    ports:
      - '8002:8002'
    command: daphne -b 0.0.0.0 -p 8002 --ws-protocol "graphql-ws" --proxy-headers ezl.asgi:channel_layer
  ws-worker:
    image: ezl:latest
    volumes:
      - .:/app
      - ezl-logs:/var/log/ezl
    command: python manage.py runworker
  luigi:
    command: luigid
    environment:
      ENV: development
    ports:
      - "8082:8082"
  flower:
    ports:
      - "8083:8083"
    environment:
      ENV: development
  tasks:
    environment:
      ENV: development
      PYTHONPATH: /app
    depends_on:
      - builder
      - db
      - tunnel
      - queues

  tunnel:
    image: ezl:latest
    command: python -m sshtunnel -U dev -P dev@2016 -L 0.0.0.0:2000 -R 172.27.155.22:1433 -p 22 201.86.113.86
    ports:
      - "2000:2000"
    volumes:
      - .:/app
    depends_on:
      - builder

  nginx:
    ports:
      - "8080:80"
    volumes:
      - ./containers/nginx/conf.d/ezl_dev.conf:/etc/nginx/conf.d/default.conf
      - web-static:/usr/share/nginx/html/staticfiles
      - web-media:/usr/share/nginx/html/media
      - /mnt/windows_ecm/Pastas:/usr/share/nginx/html/media/ECM/Pastas

  db:
    ports:
      - "57002:5432"
