version: "3"
services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - certbot
  web:
    build:
      context: .
      dockerfile: containers/web/Dockerfile
      args:
        requirements_file: production.txt
    image: ezl:latest
    command: uwsgi --ini /app/config/uwsgi/uwsgi.ini
    environment:
      ENV: production
  certbot:
    build:
      context: .
      dockerfile: containers/certbot/Dockerfile
    image: local_certbot:latest
    volumes:
      - letsencrypt-www:/tmp/www
      - letsencrypt-etc:/etc/letsencrypt
