version: "3"
services:
  builder:
    build:
      context: .
      dockerfile: containers/web/Dockerfile
      args:
        requirements_file: production.txt
    image: ezl:latest
    command: date
    environment:
      ENV: production

  nginx:
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - certbot

  web:
    build:
      context: .
      dockerfile: containers/web/Dockerfile
      args:
        requirements_file: production.txt
    image: ezl:latest
    command: uwsgi --ini /app/config/uwsgi/uwsgi.ini
    volumes:
      - .:/app
      - web-static:/app/staticfiles
      - web-media:/app/media
      - ezl-logs:/var/log/ezl
      - /mnt/windows_ecm/Agenda:/app/media/ECM
      - /mnt/windows_ecm/Pastas:/app/media/ECM/Pastas
    environment:
      ENV: production
  ws:
    image: ezl:latest
    volumes:
      - .:/app
      - ezl-logs:/var/log/ezl
    ports:
      - '8002:8002'
    command: daphne -b 0.0.0.0 -p 8002 --ws-protocol "graphql-ws" --proxy-headers ezl.asgi:channel_layer
  ws-worker:
    image: ezl:latest
    volumes:
      - .:/app
      - ezl-logs:/var/log/ezl
    command: python manage.py runworker
  luigi:
    environment:
      ENV: production

  certbot:
    build:
      context: .
      dockerfile: containers/certbot/Dockerfile
    image: local_certbot:latest
    volumes:
      - letsencrypt-www:/tmp/www
      - letsencrypt-etc:/etc/letsencrypt

  tasks:
    environment:
      ENV: production
      PYTHONPATH: /app
    depends_on:
      - builder
      - db
      - queues
