version: "3"
networks:
  default:
services:
  builder:
    build:
      context: .
      dockerfile: containers/web/Dockerfile
      args:
        requirements_file: production.txt
    image: ezl:latest
    command: date
    environment:
      ENV: production

  db:
    ports:
      - "57002:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./containers/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./containers/db/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf"
  nginx:
    depends_on:
      - web
      - certbot
    labels:
      - "traefik.backend=ezl-production"
      - "traefik.frontend.rule=Host:mtostes.ezlawyer.com.br,ezl.ezlawyer.com.br"
      - "traefik.docker.network=traefik_webgateway"
      - "traefik.enable=true"
  web:
    build:
      context: .
      dockerfile: containers/web/Dockerfile
      args:
        requirements_file: production.txt
    image: ezl:latest
    command: uwsgi --ini /app/config/uwsgi/uwsgi.ini -b 8192
    volumes:
      - .:/app
      - web-static:/app/staticfiles
      - web-media:/app/media
      - ezl-logs:/var/log/ezl
      - /mnt/windows_ecm/Agenda:/app/media/ECM
      - /mnt/windows_ecm/Pastas:/app/media/ECM/Pastas
    environment:
      ENV: production
      WORKFLOW_EMAIL: "https://ezl.ezlawyer.com.br"
  ws:
    image: ezl:latest
    volumes:
      - .:/app
      - ezl-logs:/var/log/ezl
    ports:
      - '8002:8002'
    command: daphne -b 0.0.0.0 -p 8002 --ws-protocol "graphql-ws" --proxy-headers ezl.asgi:channel_layer
  ws-worker:
    image: ezl:latest
    volumes:
      - .:/app
      - ezl-logs:/var/log/ezl
    command: python manage.py runworker
  luigi:
    environment:
      ENV: production
    ports:
      - "8082:8082"
  flower:
    ports:
      - "5555:5555"
    environment:
      ENV: production
  certbot:
    build:
      context: .
      dockerfile: containers/certbot/Dockerfile
    image: local_certbot:latest
    volumes:
      - letsencrypt-www:/tmp/www
      - letsencrypt-etc:/etc/letsencrypt

  tasks:
    environment:
      ENV: production
      PYTHONPATH: /app
    volumes:
      - .:/app
      - /mnt/windows_ecm/Agenda:/app/media/ECM
      - /mnt/windows_ecm/Pastas:/app/media/ECM/Pastas      
      - ./media/service_price_table:/app/media/service_price_table
      - ezl-logs:/var/log/ezl
    depends_on:
      - builder
      - db
      - queues
  tasks2:
    environment:
      ENV: production
      PYTHONPATH: /app
    volumes:
      - .:/app
      - /mnt/windows_ecm/Agenda:/app/media/ECM
      - /mnt/windows_ecm/Pastas:/app/media/ECM/Pastas      
      - ./media/service_price_table:/app/media/service_price_table
      - ezl-logs:/var/log/ezl
    depends_on:
      - builder
      - db
      - queues
  tasks3:
    environment:
      ENV: production
      PYTHONPATH: /app
    volumes:
      - .:/app
      - /mnt/windows_ecm/Agenda:/app/media/ECM
      - /mnt/windows_ecm/Pastas:/app/media/ECM/Pastas      
      - ./media/service_price_table:/app/media/service_price_table
      - ezl-logs:/var/log/ezl      
    depends_on:
      - builder
      - db
      - queues
  tasks4:
    image: ezl:latest
    environment:
      ENV: production
      PYTHONPATH: /app
    command: celery -A ezl worker -l debug --concurrency 10 -P eventlet -Ofair -n worker4@%h
    volumes:
      - .:/app
      - /mnt/windows_ecm/Agenda:/app/media/ECM
      - /mnt/windows_ecm/Pastas:/app/media/ECM/Pastas      
      - ./media/service_price_table:/app/media/service_price_table
      - ezl-logs:/var/log/ezl
    depends_on:
      - builder
      - db
      - queues

  queues:
    ports:
      - "8083:15672"
      - "5672:5672"

  tasks-schedule:
    environment:
      ENV: production
      PYTHONPATH: /app
    volumes:
      - .:/app
      - /mnt/windows_ecm/Agenda:/app/media/ECM
      - /mnt/windows_ecm/Pastas:/app/media/ECM/Pastas      
      - ./media/service_price_table:/app/media/service_price_table
      - ezl-logs:/var/log/ezl      

  pgweb:
    build:
      context: .
      dockerfile: containers/pgweb/Dockerfile
    command: pgweb --url postgres://ezl:ezl@db:5432/ezl?sslmode=disable --bind 0.0.0.0 --auth-user=admin --auth-pass=dev@2016
    ports:
    - "9002:8081"
