version: "3"

volumes:
  db-data:
  db-advwin-data:
  web-media:
  web-static:
  letsencrypt-www:
  letsencrypt-etc:
  ezl-logs:

networks:
  gateway:
    external:
      name: traefik_webgateway

services:
  web:
    image: ezl:latest
    volumes:
      - .:/app
      - ./media/service_price_table:/app/media/service_price_table
      - web-static:/app/staticfiles
      - web-media:/app/media
      - ezl-logs:/var/log/ezl
      - /mnt/windows_ecm/Agenda:/app/media/ECM
      - /mnt/windows_ecm/Pastas:/app/media/ECM/Pastas
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
  ws:
    image: ezl:latest
    volumes:
      - .:/app
      - ezl-logs:/var/log/ezl
    command: daphne -b 0.0.0.0 -p 8002 --ws-protocol "graphql-ws" --proxy-headers ezl.asgi:channel_layer
  ws-worker:
    image: ezl:latest
    volumes:
      - .:/app
      - ezl-logs:/var/log/ezl
    command: python manage.py runworker
  luigi:
    build:
      context: .
      dockerfile: containers/luigi/Dockerfile
    command: bash -c "cron && crontab /etc/cron.d/luigi && luigid"
    volumes:
      - .:/app
      - ./containers/luigi/cron:/etc/cron.d/luigi
      - ezl-logs:/var/log/ezl
      - /mnt/windows_ecm/Agenda:/app/media/ECM
      - /mnt/windows_ecm/Pastas:/app/media/ECM/Pastas
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    depends_on:
      - builder
      - db

  tasks:
    image: ezl:latest
    command: celery -A ezl worker -l debug --concurrency 10 -P eventlet -Ofair -n worker1@%h
    volumes:
      - .:/app
      - ./media/service_price_table:/app/media/service_price_table
      - ezl-logs:/var/log/ezl
    depends_on:
      - builder
      - db
      - queues

  tasks-schedule:
    image: ezl:latest
    command: celery -A ezl beat -l info
    volumes:
      - .:/app
      - ezl-logs:/var/log/ezl
    depends_on:
      - tasks

  flower:
    image: ezl:latest
    command: celery flower --broker=amqp://guest:guest@queues:5672// --broker_api=http://guest:guest@localhost:8083/api --port=5555 --inspect_timeout=60000 --basic_auth=ezl:flower@ezl
    volumes:
      - .:/app
    depends_on:
      - tasks

  queues:
    restart: unless-stopped
    image: "rabbitmq:3-management"
    ports:
      - "8083:15672"
      - "5672:5672"

  nginx:
    image: nginx:1.13
    labels:
      - "traefik.backend=ezl"
      - "traefik.frontend.rule=Host:ezl.local"
      - "traefik.docker.network=traefik_webgateway"
    volumes:
      - ./containers/nginx/conf.d/ezl.conf:/etc/nginx/conf.d/default.conf
      - web-static:/usr/share/nginx/html/static
      - web-media:/usr/share/nginx/html/media
      - letsencrypt-www:/usr/share/nginx/html/certbot
      - letsencrypt-etc:/etc/letsencrypt
      - /mnt/windows_ecm/Agenda:/usr/share/nginx/html/media/ECM
      - /mnt/windows_ecm/Pastas:/usr/share/nginx/html/media/ECM/Pastas
    depends_on:
      - web
    networks:
      - gateway
      - default

  db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: ezl
      POSTGRES_USER: ezl
      POSTGRES_PASSWORD: ezl
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./containers/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

  redis:
    image: redis:4.0.6
    volumes:
      - ".containers/redis/redis.conf:/etc/redis/redis.conf"

#  db_advwin:
#    image: microsoft/mssql-server-linux:2017-latest
#    environment:
#      ACCEPT_EULA: Y
#      MSSQL_SA_PASSWORD: DB@advwinOn1Tw2Thre3
#    volumes:
#      - "db-advwin-data:/var/opt/mssql"
