version: "3"

volumes:
  db-data:
  db-advwin-data:
  web-media:
  web-static:
  letsencrypt-www:
  letsencrypt-etc:

services:
  web:
    volumes:
      - .:/app
      - web-static:/app/staticfiles
      - web-media:/app/media
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    depends_on:
      - db

  nginx:
    image: nginx:1.13
    volumes:
      - ./containers/nginx/conf.d/ezl.conf:/etc/nginx/conf.d/default.conf
      - web-static:/usr/share/nginx/html/static
      - web-media:/usr/share/nginx/html/media
      - letsencrypt-www:/usr/share/nginx/html/certbot
      - letsencrypt-etc:/etc/letsencrypt
    depends_on:
      - web

  db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: ezl
      POSTGRES_USER: ezl
      POSTGRES_PASSWORD: ezl
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./containers/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

  rabbit:
    restart: unless-stopped
    image: rabbitmq:latest
    ports:
      - 5672:5672

#  db_advwin:
#    image: microsoft/mssql-server-linux:2017-latest
#    environment:
#      ACCEPT_EULA: Y
#      MSSQL_SA_PASSWORD: DB@advwinOn1Tw2Thre3
#    volumes:
#      - "db-advwin-data:/var/opt/mssql"
