version: "3"
services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - certbot
  web:
    build:
      context: .
      dockerfile: containers/web/Dockerfile
    image: ezl:latest
    command: uwsgi --ini /app/config/uwsgi/uwsgi.ini
    environment:
      ENV: production
  certbot:
    image: certbot/certbot
    command: certonly --webroot -w /tmp/www -d mtostes.ezlawyer.com.br -m contato@ezlawyer.com.br --agree-tos
    volumes:
      - letsencrypt-www:/tmp/www
      - letsencrypt-etc:/etc/letsencrypt
