version: "3"

services:
  web:
    build:
      context: .
      dockerfile: containers/web/Dockerfile
      args:
        requirements_file: development.txt
    image: ezl:dev
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      ENV: development
    ports:
      - "8000:8000"

  luigi:
    image: ezl:dev
    command: luigid
    environment:
      ENV: development
    volumes:
      - .:/app
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

  nginx:
    ports:
      - "8080:80"
    volumes:
      - ./containers/nginx/conf.d/ezl_dev.conf:/etc/nginx/conf.d/default.conf
      - web-static:/usr/share/nginx/html/staticfiles
      - web-media:/usr/share/nginx/html/media
