version: "3"
services:
  nginx:
    ports:
      - "801:80"
      - "4431:443"
    volumes:
      - ./containers/nginx/conf.d/ezl_teste.conf:/etc/nginx/conf.d/default.conf
      - web-static:/usr/share/nginx/html/static
      - web-media:/usr/share/nginx/html/media
      - letsencrypt-www:/usr/share/nginx/html/certbot
      - letsencrypt-etc:/etc/letsencrypt
    depends_on:
      - web
      - certbot

  web:
    build:
      context: .
      dockerfile: containers/web/Dockerfile
      args:
        requirements_file: production.txt
    image: ezl:latest
    command: uwsgi --ini /app/config/uwsgi/uwsgi.ini
    environment:
      ENV: development

  tasks:
    depends_on:
      - db
      - tunnel
      - queues

  tunnel:
    image: ezl:latest
    command: python -m sshtunnel -U dev -P dev@2016 -L 0.0.0.0:2000 -R 172.27.155.9:1433 -p 22 201.86.113.86
    ports:
      - "2000:2000"
    volumes:
      - .:/app

  certbot:
    build:
      context: .
      dockerfile: containers/certbot/Dockerfile
    image: local_certbot:latest
    volumes:
      - letsencrypt-www:/tmp/www
      - letsencrypt-etc:/etc/letsencrypt
