# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 16:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_auto_20170520_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='auth_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                       to=settings.AUTH_USER_MODEL, verbose_name='Usuário do sistema'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=255, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_corresponding',
            field=models.BooleanField(default=False, verbose_name='É Correspondente?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_court',
            field=models.BooleanField(default=False, verbose_name='É Tribunal?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_lawyer',
            field=models.BooleanField(default=False, verbose_name='É Advogado?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='legal_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Razão social/nome completo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='legal_type',
            field=models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome Fantasia/Apelido'),
        ),
    ]
