# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170517_1718'),
        ('core', '0002_auto_20170517_2026'),
    ]

    operations = [
    ]
