# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20170526_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='is_corresponding',
            new_name='is_correspondent',
        ),
        migrations.AlterField(
            model_name='person',
            name='legal_type',
            field=models.CharField(
                choices=[('J', 'Jurídica'), ('F', 'Física')],
                max_length=1,
                verbose_name='Tipo'),
        ),
    ]
