# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170531_1552'),
        ('core', '0005_auto_20170531_1935'),
    ]

    operations = []
