# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20170607_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='active',
        ),
        migrations.RemoveField(
            model_name='addresstype',
            name='active',
        ),
        migrations.RemoveField(
            model_name='city',
            name='active',
        ),
        migrations.RemoveField(
            model_name='contactmechanism',
            name='active',
        ),
        migrations.RemoveField(
            model_name='contactmechanismtype',
            name='active',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='active',
        ),
        migrations.RemoveField(
            model_name='country',
            name='active',
        ),
        migrations.RemoveField(
            model_name='person',
            name='active',
        ),
        migrations.RemoveField(
            model_name='state',
            name='active',
        ),
        migrations.AddField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='addresstype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='contactmechanism',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='contactmechanismtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='state',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='legal_type',
            field=models.CharField(
                choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=1, verbose_name='Tipo'),
        ),
    ]
