# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170607_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': [
                '-id'], 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterField(
            model_name='person',
            name='legal_type',
            field=models.CharField(
                choices=[('J', 'Jurídica'), ('F', 'Física')], max_length=1, verbose_name='Tipo'),
        ),
    ]
