# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_merge_20170613_1415'),
        ('core', '0013_auto_20170613_1409'),
    ]

    operations = []
