# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0016_auto_20170613_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='legal_type',
            field=models.CharField(
                choices=[('F', 'Física'), ('J', 'Jurídica')],
                max_length=1,
                verbose_name='Tipo'),
        ),
    ]
