# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20170621_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='service_type',
            field=models.CharField(
                choices=[('F', 'Fornecedor'), ('C', 'Cliente')],
                default='C',
                max_length=1,
                verbose_name='Tipo de Serviço'),
        ),
        migrations.AlterField(
            model_name='person',
            name='legal_type',
            field=models.CharField(
                choices=[('F', 'Física'), ('J', 'Jurídica')],
                max_length=1,
                verbose_name='Tipo'),
        ),
    ]
