# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20170621_2245'),
        ('core', '0025_auto_20170622_1001'),
    ]

    operations = []
