# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0023_auto_20170622_1615'),
        ('core', '0025_auto_20170622_1001'),
    ]

    operations = [
    ]
