# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20170623_0955'),
        ('core', '0023_auto_20170622_1615'),
    ]

    operations = []
