# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20170625_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='service_type',
        ),
        migrations.AddField(
            model_name='person',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='É Cliente?'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_provider',
            field=models.BooleanField(default=False, verbose_name='É Fornecedor?'),
        ),
    ]
