# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20170625_2241'),
        ('core', '0026_merge_20170626_1525'),
    ]

    operations = []
