# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0033_auto_20170626_1601'),
        ('core', '0032_merge_20170626_1551'),
    ]

    operations = []
