# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0034_merge_20170626_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='service_type',
        ),
        migrations.AlterField(
            model_name='person',
            name='legal_type',
            field=models.CharField(
                choices=[('J', 'Jurídica'), ('F', 'Física')],
                max_length=1,
                verbose_name='Tipo'),
        ),
    ]
