# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0043_auto_20170709_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Cidade'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'País'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Estado'},
        ),
    ]
