# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-19 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0045_auto_20170802_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelExportHistory',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('model', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
