# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20170918_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_correspondent',
        ),
        migrations.AlterField(
            model_name='contactmechanism',
            name='notes',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
