# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20171004_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços'
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_court',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='core.AddressType',
                verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='core.City',
                verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city_region',
            field=models.CharField(max_length=255, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='address',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=255, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=255, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name='Nome Fantasia/Apelido'),
        ),
    ]
