# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-22 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20171011_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={
                'ordering': ['legal_name', 'name'],
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas'
            },
        ),
    ]
