# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20171219_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Person')),
                ('persons', models.ManyToManyField(related_name='offices', to='core.Person')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.person',),
        ),
    ]
