# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='persons',
            field=models.ManyToManyField(blank=True, related_name='offices', to='core.Person'),
        ),
    ]
