# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20171206_1746'),
        ('core', '0052_auto_20171219_1640'),
    ]

    operations = [
    ]
