# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20171206_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='core.Country',
                verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='core.State',
                verbose_name='Estado'),
        ),
    ]
