# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-10 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20180102_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='import_from_legacy',
            field=models.BooleanField(
                default=False, verbose_name='Importar registros?'),
        ),
    ]
