# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('A', 'ACCEPT'), ('R', 'REFUSED'), ('N', 'NOt REVIEWED')], default='N', max_length=1),
        ),
    ]
