# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20180102_1117'),
        ('core', '0056_invite_status'),
    ]

    operations = [
    ]
