# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20180115_1440'),
        ('core', '0059_auto_20180117_0957'),
    ]

    operations = [
    ]
