# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0060_invite_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário do sistema')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defaultoffice_office', to='core.Office', verbose_name='Escritório')),
            ],
            options={
                'verbose_name': 'Escritório Padrão',
                'verbose_name_plural': 'Escritórios Padrão',
            },
        ),
        migrations.AddField(
            model_name='defaultoffice',
            name='alter_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='defaultoffice',
            name='alter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='defaultoffice_alter_user', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Alterado por'),
        ),
        migrations.AddField(
            model_name='defaultoffice',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultoffice',
            name='create_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='defaultoffice_create_user', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Criado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultoffice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
