# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20180112_1653'),
        ('core', '0061_auto_20180117_1523'),
    ]

    operations = [
    ]
