# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_defaultoffice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.Office'),
        ),
    ]
