# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20180112_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpf_cnpj',
            field=models.CharField(
                blank=True, max_length=255, null=True,
                verbose_name='CPF/CNPJ'),
        ),
    ]
