# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20180119_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adresses', to='core.Office'),
        ),
        migrations.AlterField(
            model_name='address',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CPF/CNPJ'),
        ),
    ]
