# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_office_import_from_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invites', to='core.Office', verbose_name='Escritório'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invites', to='core.Person', verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('A', 'ACCEPTED'), ('R', 'REFUSED'), ('N', 'NOT REVIEWED')], default='N', max_length=1, verbose_name='Status'),
        ),
    ]
