# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20180119_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='import_from_legacy',
            field=models.BooleanField(
                default=False,
                verbose_name=
                'Importar OSs do sistema de origem para esse cliente'),
        ),
    ]
