# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_inviteoffice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresstype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='inviteoffice',
            options={'verbose_name': 'Convites para escritórios'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={
                'ordering': ['name'],
                'verbose_name': 'Estado'
            },
        ),
    ]
