# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20180220_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='invite',
            name='invite_code',
            field=models.CharField(blank=True, default=core.models._create_hash, max_length=50, null=True, unique=True,
                                   verbose_name='Código do convite'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invites', to='core.Person', verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.CharField(
                choices=[('A', 'ACCEPTED'), ('R', 'REFUSED'), ('N', 'NOT REVIEWED'), ('E', 'EXTERNAL')], default='N',
                max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='inviteoffice',
            name='status',
            field=models.CharField(
                choices=[('A', 'ACCEPTED'), ('R', 'REFUSED'), ('N', 'NOT REVIEWED'), ('E', 'EXTERNAL')], default='N',
                max_length=1, verbose_name='Status'),
        ),
    ]
