# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-07 13:56
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20180301_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invite_code',
            field=models.CharField(blank=True, default=core.models._create_hash, max_length=50, null=True, unique=True, verbose_name='Código do convite'),
        ),
    ]
