# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_auto_20180509_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='invite_from',
            field=models.CharField(choices=[('P', 'PERSON'), ('O', 'OFFICE')], default='O', max_length=1, verbose_name='Origem do convite'),
        ),
    ]
