# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_invite_invite_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmechanism',
            options={'verbose_name': 'Mecanismo de contato',
                     'verbose_name_plural': 'Mecanismos de contato'},
        ),
        migrations.AlterField(
            model_name='contactmechanism',
            name='contact_mechanism_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='core.ContactMechanismType', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='contactmechanism',
            name='description',
            field=models.CharField(
                max_length=255, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='contactmechanism',
            name='notes',
            field=models.CharField(
                blank=True, max_length=400, verbose_name='Observações'),
        ),
    ]
