# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_auto_20180509_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='public_office',
            field=models.BooleanField(
                default=False, verbose_name='Escritório público'),
        ),
    ]
