# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-10 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_office_public_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmechanismtype',
            name='type_contact_mechanism',
            field=models.CharField(
                choices=[('0', '-'), ('1', 'TELEFONE'), ('2', 'E-MAIL'),
                         ('3', 'SKYPE'), ('4', 'WHATSAPP'), ('5', 'FACEBOOK'),
                         ('6', 'SITE'), ('7', 'LINKEDIN'), ('8', 'INSTAGRAM'),
                         ('9', 'SNAPCHAT')],
                default='0',
                max_length=1,
                verbose_name='Tipo'),
        ),
    ]
