# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_office_public_ezlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmechanismtype',
            name='type_contact_mechanism',
        ),
        migrations.AddField(
            model_name='contactmechanismtype',
            name='type_contact_mechanism_type',
            field=models.IntegerField(choices=[(1, 'INVÁLIDO'), (2, 'TELEFONE'), (3, 'E-MAIL'), (4, 'SKYPE'), (5, 'WHATSAPP'), (6, 'FACEBOOK'), (7, 'SITE'), (8, 'LINKEDIN'), (9, 'INSTAGRAM'), (10, 'SNAPCHAT')], default=2, verbose_name='Tipo'),
        ),
    ]
