# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='team_office', to='core.Office', verbose_name='Escritório'),
            preserve_default=False,
        ),
    ]
