# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 00:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0084_team_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='users',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='supervisors',
            field=models.ManyToManyField(related_name='team_supervisors', to=settings.AUTH_USER_MODEL),
        ),
    ]
