# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 06:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20180614_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(
                related_name='team_members',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Membros'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Equipe'),
        ),
        migrations.AlterField(
            model_name='team',
            name='supervisors',
            field=models.ManyToManyField(
                related_name='team_supervisors',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Supervisores'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('office', 'name')]),
        ),
    ]
