# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20180618_0506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes'
            },
        ),
    ]
