# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_auto_20180625_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='person',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.Person'),
        ),
        migrations.AlterField(
            model_name='contactmechanism',
            name='person',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.Person'),
        ),
        migrations.AlterField(
            model_name='defaultoffice',
            name='auth_user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Usuário do sistema'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='person',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='invites',
                to='core.Person',
                verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='office',
            name='auth_user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Usuário do sistema'),
        ),
        migrations.AlterField(
            model_name='person',
            name='auth_user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Usuário do sistema'),
        ),
    ]
