# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_auto_20180703_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='use_service',
            field=models.BooleanField(default=True, verbose_name='Possuo equipe de conferência de dados na delegação e validação da OS'),
        ),
    ]
