# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0090_auto_20180711_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlFirstAccessUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_login', models.DateTimeField(auto_now_add=True, verbose_name='Data do primeiro acesso.')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário do sistema')),
            ],
            options={
                'verbose_name': 'Controle de primeiro acesso',
                'verbose_name_plural': 'Controle de primeiro acesso',
            },
        ),
    ]
