# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_controlfirstaccessuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='use_service',
            field=models.BooleanField(default=True, verbose_name='Possuo equipe de conferência de dados na delegação e validação da OS'),
        ),
        migrations.AddField(
            model_name='office',
            name='use_etl',
            field=models.BooleanField(default=True,
                                      verbose_name='Possuo processo de importação de dados de outros sistemas'),
        ),
    ]
