# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_controlfirstaccessuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='alter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por'),
        ),
        migrations.AlterField(
            model_name='person',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
