# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_auto_20180711_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='use_etl',
            field=models.BooleanField(default=True, verbose_name='Possuo processo de importação de dados de outros sistemas'),
        ),
    ]
