# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 20:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_externalapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapplication',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Office', verbose_name='Escritório'),
        ),
        migrations.AlterField(
            model_name='externalapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_externalapplication', to=settings.AUTH_USER_MODEL),
        ),
    ]
