# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_auto_20180903_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsettings',
            name='i_work_alone',
            field=models.BooleanField(default=True),
        ),
    ]
