# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_auto_20180814_1737'),
        ('core', '0089_officeapplication'),
    ]

    operations = [
    ]
