# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_merge_20180816_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officeapplication',
            name='office',
        ),
        migrations.RemoveField(
            model_name='officeapplication',
            name='user',
        ),
        migrations.DeleteModel(
            name='OfficeApplication',
        ),
    ]
