# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0097_person_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUsers',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('company',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='users',
                     to='core.Company',
                     verbose_name='Empresa')),
                ('user',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Usuário')),
            ],
        ),
    ]
