# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_office_use_service_use_etl'),
        ('core', '0098_office_logo'),
    ]

    operations = [
    ]
