# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_auto_20180809_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='companys',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Usuário'),
        ),
    ]
