# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_office_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='companyuser',
            options={'verbose_name': 'Usuario da empresa', 'verbose_name_plural': 'Usuário das empresas'},
        ),
        migrations.AlterModelOptions(
            name='externalapplication',
            options={'verbose_name': 'Aplicação externa', 'verbose_name_plural': 'Aplicações externas'},
        ),
    ]
