# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_customsettings_task_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsettings',
            name='task_settings',
        ),
    ]
