# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-10 20:36
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0109_auto_20180905_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportXlsFile',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('create_date',
                 models.DateTimeField(
                     auto_now_add=True, verbose_name='Criado em')),
                ('alter_date',
                 models.DateTimeField(
                     auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active',
                 models.BooleanField(default=True, verbose_name='Ativo')),
                ('file_xls',
                 models.FileField(
                     upload_to=core.models.get_dir_name,
                     verbose_name='Arquivo')),
                ('log', models.TextField(null=True, verbose_name='Log')),
                ('start',
                 models.DateTimeField(verbose_name='Início processo')),
                ('end',
                 models.DateTimeField(null=True, verbose_name='Fim processo')),
                ('alter_user',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='importxlsfile_alter_user',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Alterado por')),
                ('create_user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='importxlsfile_create_user',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Criado por')),
                ('office',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='importxlsfile_office',
                     to='core.Office',
                     verbose_name='Escritório')),
            ],
            options={
                'verbose_name': 'Arquivos Importados para inserção em lote',
            },
        ),
    ]
