# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_auto_20180925_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='refunds_correspondent_service',
            field=models.BooleanField(default=False, verbose_name='Cliente reembolsa valor gasto com serviço de correspondência'),
        ),
    ]
