# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 20:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_person_refunds_correspondent_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsettings',
            name='default_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário default'),
        ),
    ]
