# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_auto_20181029_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='court_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lawsuit.CourtDistrict', verbose_name='Comarca'),
        ),
    ]
