# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_fixture_email_template_custom_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsettings',
            name='default_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person', verbose_name='Cliente padrão'),
        ),
    ]
