# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 13:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_create_default_customer_default_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importxlsfile',
            name='log',
        ),
        migrations.AddField(
            model_name='importxlsfile',
            name='log_file',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Log do processo'),
        ),
    ]
