# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0120_create_default_customer_default_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do grupo')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='officenetwork_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='officenetwork_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('members', models.ManyToManyField(related_name='network_members', to='core.Office', verbose_name='Membros')),
            ],
            options={
                'verbose_name': 'Grupo de Escritórios',
                'verbose_name_plural': 'Grupos de Escritórios',
            },
        ),
    ]
