# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_officenetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfExpertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=2555, verbose_name='Área de atuação')),
                ('offices', models.ManyToManyField(blank=True, to='core.Office')),
            ],
            options={
                'verbose_name': 'Áreas de atuação',
            },
        ),
    ]
