# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-17 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0121_officenetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeOffices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='officeoffices_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='officeoffices_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('from_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_offices', to='core.Office')),
                ('person_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
                ('to_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_offices', to='core.Office')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='office',
            name='offices_related',
            field=models.ManyToManyField(blank=True, through='core.OfficeOffices', to='core.Office'),
        ),
    ]
