# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-13 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_areaofexpertise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaofexpertise',
            options={'ordering': ['area'], 'verbose_name': 'Áreas de atuação'},
        ),
    ]
