# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-17 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_receate_offices_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='offices',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='offices_related',
            new_name='offices',
        ),
    ]
