# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_clean_cpf_cnpj_office'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaofexpertise',
            options={'ordering': ['area'], 'verbose_name': 'Área de atuação', 'verbose_name_plural': 'Áreas de atuação'},
        ),
    ]
