# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-25 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_clean_cpf_cnpj_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='show_administrative_menus',
            field=models.BooleanField(default=False, verbose_name='Mostrar menus administrativos'),
        ),
    ]
