# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-19 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0132_companyuser_show_administrative_menus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('initial_date', models.DateTimeField(verbose_name='Data inicial')),
                ('finish_date', models.DateTimeField(verbose_name='Data final')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custommessage_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custommessage_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Mensagens Customizadas',
            },
        ),
    ]
