# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_companyuser_show_administrative_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsettings',
            name='email_to_notification',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail para receber notificações'),
        ),
    ]
