# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_auto_20190325_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='use_etl',
            new_name='use_etl_old',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='use_service',
            new_name='use_service_old',
        ),
        migrations.AlterField(
            model_name='customsettings',
            name='default_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário default'),
        ),
    ]
