# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-19 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_custommessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custommessage',
            name='alter_date',
        ),
        migrations.RemoveField(
            model_name='custommessage',
            name='alter_user',
        ),
        migrations.RemoveField(
            model_name='custommessage',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='custommessage',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='custommessage',
            name='is_active',
        ),
    ]
