# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-26 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_auto_20190319_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custommessage',
            options={'verbose_name': 'Mensagens Customizadas', 'verbose_name_plural': 'Mensagens Customizadas'},
        ),
        migrations.AddField(
            model_name='custommessage',
            name='title',
            field=models.CharField(default='title', max_length=255, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
