# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_auto_20190326_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsettings',
            name='show_task_in_admin_dash',
            field=models.BooleanField(default=True, verbose_name='Mostrar as OSs deste escritório no Dash'),
        ),
    ]
