# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_customsettings_show_task_in_admin_dash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
