# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_update_contact_mechanism_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_commission_requestor', models.FloatField(default=0.025)),
                ('rate_commission_correspondent', models.FloatField(default=0.1)),
            ],
        ),
    ]
