# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_adminsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminSettings',
        ),
    ]
