# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-18 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_adminsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='rate_commission_correspondent',
            field=models.FloatField(default=0.1, verbose_name='Taxa de comissão do correspondente'),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='rate_commission_requestor',
            field=models.FloatField(default=0.025, verbose_name='Taxa de comissão do solicitante'),
        ),
    ]
