# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardetl',
            old_name='execution_date_initial',
            new_name='execution_date_start',
        ),
    ]
