# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_auto_20171121_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardetl',
            name='execution_date_finish',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='dashboardetl',
            name='execution_date_start',
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name='Inicio'),
        ),
    ]
