# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_auto_20171122_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardetl',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
