# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_dashboardetl_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardetl',
            name='imported_quantity',
            field=models.IntegerField(
                default=0, verbose_name='Quantidade importada'),
        ),
        migrations.AddField(
            model_name='dashboardetl',
            name='read_quantity',
            field=models.IntegerField(
                default=0, verbose_name='Quantidade Lida'),
        ),
    ]
