# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_auto_20171122_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardetl',
            name='executed_query',
            field=models.TextField(blank=True, null=True, verbose_name='Query executada'),
        ),
    ]
