# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etl', '0007_dashboardetl_executed_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorETL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Descrição do erro')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erroretl_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erroretl_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='dashboardetl',
            name='executed_query',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Query executada'),
        ),
        migrations.AlterField(
            model_name='dashboardetl',
            name='execution_date_finish',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='dashboardetl',
            name='imported_quantity',
            field=models.IntegerField(default=0, editable=False, verbose_name='Quantidade importada'),
        ),
        migrations.AlterField(
            model_name='dashboardetl',
            name='name',
            field=models.CharField(editable=False, max_length=100, verbose_name='ETL'),
        ),
        migrations.AlterField(
            model_name='dashboardetl',
            name='read_quantity',
            field=models.IntegerField(default=0, editable=False, verbose_name='Quantidade Lida'),
        ),
        migrations.AlterField(
            model_name='dashboardetl',
            name='status',
            field=models.BooleanField(default=True, editable=False, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='erroretl',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.DashboardETL', verbose_name='Erros'),
        ),
    ]
