# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0008_auto_20171123_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardetl',
            options={
                'ordering': ('-execution_date_start', ),
                'verbose_name': 'Dashboard ETL',
                'verbose_name_plural': 'Dashboard ETL'
            },
        ),
        migrations.AlterField(
            model_name='dashboardetl',
            name='execution_date_start',
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='erroretl',
            name='error',
            field=models.TextField(
                blank=True,
                editable=False,
                null=True,
                verbose_name='Descrição do erro'),
        ),
        migrations.AlterField(
            model_name='erroretl',
            name='log',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='errors',
                to='etl.DashboardETL',
                verbose_name='Erros'),
        ),
    ]
