# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0009_auto_20171127_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardetl',
            name='db_host_source',
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                verbose_name='Host do db de origem'),
        ),
        migrations.AddField(
            model_name='dashboardetl',
            name='db_name_source',
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name='DB de origem'),
        ),
    ]
