# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_office'),
        ('etl', '0011_inconsistencyetl'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardetl',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='dashboardetl_office', to='core.Office', verbose_name='Escritório'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inconsistencyetl',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='inconsistencyetl_office', to='core.Office', verbose_name='Escritório'),
            preserve_default=False,
        ),
    ]
