# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0013_auto_20181003_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardetl',
            name='db_host_source',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Host do db de origem'),
        ),
    ]
