# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0014_auto_20190130_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inconsistencyetl',
            name='inconsistency',
            field=models.CharField(blank=True, choices=[('OS sem movimentação', 'Tasklessmovement'), ('Movimentação sem processo', 'Movementlessprocess'), ('OS em Pasta Inativa', 'Taskinativefolder'), ('O valor preenchido no campo comarca não foi encontrado como Comarca, Cidade ou Complemento de comarca', 'Invalidcourtdistrict'), ('O campo comarca não foi preenchido', 'Blankcourtdistrict'), ('O campo prazo fatal não foi preenchido', 'Blankfinaldeadlinedate'), ('O prazo fatal da OS é menor que o mínimo configurado', 'Minhouroserror')], max_length=150, null=True, verbose_name='Inconsistência'),
        ),
    ]
