# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0039_folder_cost_center'),
        ('task', '0050_auto_20171205_1548'),
        ('core', '0051_auto_20171022_1621'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePriceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicepricetable_client', to='core.Person', verbose_name='Cliente')),
                ('correspondent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicepricetable_correspondent', to='core.Person', verbose_name='Correspondente')),
                ('court_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicepricetable_court_district', to='lawsuit.CourtDistrict', verbose_name='Comarca')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicepricetable_state', to='core.State', verbose_name='UF')),
                ('type_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicepricetable_type_task', to='task.TypeTask', verbose_name='Tipo de Serviço')),
            ],
            options={
                'verbose_name': 'Tabela de preço de serviços',
                'db_table': 'service_price_table',
                'ordering': ['id'],
                'verbose_name_plural': 'Tabelas de preço de serviços',
            },
        ),
    ]
