# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_auto_20180102_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepricetable',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor'),
        ),
    ]
