# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_costcenter_office'),
        ('financial', '0004_auto_20180102_1117'),
    ]

    operations = [
    ]
