# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20180112_1653'),
        ('task', '0061_auto_20180124_1336'),
        ('financial', '0005_auto_20180112_1653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicepricetable',
            unique_together=set([('correspondent', 'type_task')]),
        ),
    ]
