# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_auto_20180112_1653'),
        ('financial', '0006_auto_20180108_1806'),
    ]

    operations = [
    ]
