# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

def get_default_office(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    admin = User.objects.filter(username='admin').first()
    if admin:
        Office = apps.get_model('core', 'Office')
        default_office, created = Office.objects.get_or_create(create_user=admin,
                                                               cpf_cnpj='03.482.042/0001-02',
                                                               name='Marcelo Tostes Advogados Associados',
                                                               legal_name='Marcelo Tostes Advogados Associados')
        ServicePriceTable = apps.get_model('financial', 'servicepricetable')
        for record in ServicePriceTable.objects.all():
            record.office_id = default_office.id
            record.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0006_auto_20180108_1806'),
    ]

    operations = [
        migrations.RunPython(get_default_office),
    ]
