# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_merge_20180118_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepricetable',
            name='correspondent',
        ),
    ]
