# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0007_auto_20180108_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepricetable',
            name='office',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='servicepricetable_office',
                to='core.Office',
                verbose_name='Escritório'),
            preserve_default=False,
        ),
    ]
