# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def get_default_office(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    admin = User.objects.filter(username='admin').first()
    if admin:
        Office = apps.get_model('core', 'Office')
        default_office, created = Office.objects.get_or_create(create_user=admin,
                                                               cpf_cnpj='03.482.042/0001-02',
                                                               name='Marcelo Tostes Advogados Associados',
                                                               legal_name='Marcelo Tostes Advogados Associados')
        Costcenter = apps.get_model('financial', 'costcenter')
        for record in Costcenter.objects.all():
            record.office_id = default_office.id
            record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_auto_20180108_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    blank=True, null=True,
                                    related_name='costcenter_office', to='core.Office', verbose_name='Escritório'),
            preserve_default=False,
        ),
        migrations.RunPython(get_default_office),
        migrations.AlterField(
            model_name='costcenter',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    blank=False, null=False,
                                    related_name='costcenter_office', to='core.Office', verbose_name='Escritório'),
            preserve_default=False,
        )
    ]
