# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20180119_1226'),
        ('financial', '0009_costcenter_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepricetable',
            name='office_correspondent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT,
                                    null=True, related_name='office_correspondent', to='core.Office',
                                    verbose_name='Escritório Correspondente'),
        ),
    ]
