# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_office_import_from_legacy'),
        ('lawsuit', '0043_auto_20180105_1749'),
        ('task', '0064_auto_20180201_0911'),
        ('financial', '0010_servicepricetable_office_correspondent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicepricetable',
            unique_together=set([('office', 'type_task', 'client',
                                  'court_district', 'state')]),
        ),
    ]
