# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0044_auto_20180208_1532'),
        ('core', '0070_auto_20180208_1532'),
        ('task', '0070_auto_20180208_1532'),
        ('financial', '0011_auto_20180201_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(
                default='', max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterUniqueTogether(
            name='costcenter',
            unique_together=set([('name', 'office')]),
        ),
        migrations.AlterUniqueTogether(
            name='servicepricetable',
            unique_together=set([('office', 'office_correspondent',
                                  'type_task', 'client', 'court_district',
                                  'state')]),
        ),
    ]
