# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0013_auto_20180208_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepricetable',
            name='type_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicepricetable_type_task', to='task.TypeTask', verbose_name='Tipo de Serviço'),
        ),
    ]
