# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0014_change_correpondent_office_correspondent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepricetable',
            name='correspondent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='servicepricetable_correspondent',
                to='core.Person',
                verbose_name='Correspondente'),
        ),
        migrations.AlterField(
            model_name='servicepricetable',
            name='office_correspondent',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='office_correspondent',
                to='core.Office',
                verbose_name='Escritório Correspondente'),
        ),
    ]
