# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0015_auto_20180228_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepricetable',
            name='correspondent',
        ),
    ]
