# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import financial.models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0018_importservicepricetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='importservicepricetable',
            name='imported',
            field=models.BooleanField(default=False, verbose_name='Importado'),
        ),
        migrations.AlterField(
            model_name='importservicepricetable',
            name='file_xls',
            field=models.FileField(upload_to=financial.models.get_dir_name, verbose_name='Arquivo'),
        ),
    ]
