# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0019_auto_20180523_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='importservicepricetable',
            name='percent_imported',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Percent'),
        ),
    ]
