# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0051_auto_20181001_1009'),
        ('financial', '0019_auto_20180925_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepricetable',
            name='court_district_complement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicepricetable_court_district_complement', to='lawsuit.CourtDistrictComplement', verbose_name='Complemento de comarca'),
        ),
    ]
