# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0020_importservicepricetable_percent_imported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importservicepricetable',
            name='imported',
        ),
    ]
