# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0021_auto_20181018_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
