# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_person_refunds_correspondent_service'),
        ('financial', '0022_auto_20181018_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepricetable',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicepricetable_city', to='core.City', verbose_name='Cidade'),
        ),
    ]
