# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0024_servicepricetable_office_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepricetable',
            name='office_correspondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='office_correspondent', to='core.Office', verbose_name='Escritório Correspondente'),
        ),
    ]
