# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_officenetwork'),
        ('financial', '0025_auto_20181126_1723'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='costcenter',
            unique_together=set([('name', 'office', 'legacy_code')]),
        ),
    ]
