# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 13:19
from __future__ import unicode_literals
from django.db import migrations, models
import logging
logger = logging.getLogger('0028_policy_price_default')


def create_default_policy(apps, schema_editor):
    from financial.models import CategoryPrice, BillingType, BillingMoment
    from django.contrib.auth.models import User
    PolicyPrice = apps.get_model('financial', 'PolicyPrice')
    ServicePriceTable = apps.get_model('financial', 'ServicePriceTable')
    Office = apps.get_model('core', 'Office')
    policys_price = []
    admin_user = User.objects.get(username='admin')    
    # Criando politicas de preco
    for office in Office.objects.all():
        policy_default = PolicyPrice(
            office=office, 
            create_user_id=admin_user.pk,
            name=CategoryPrice.DEFAULT,
            category=CategoryPrice.DEFAULT, 
            billing_type=BillingType.PER_UNIT, 
            billing_moment=BillingMoment.PRE_PAID)
        policys_price.append(policy_default)
        policy_public = PolicyPrice(
            office=office, 
            create_user_id=admin_user.pk,
            name=CategoryPrice.PUBLIC,
            category=CategoryPrice.PUBLIC, 
            billing_type=BillingType.PER_UNIT, 
            billing_moment=BillingMoment.PRE_PAID
        )
        policys_price.append(policy_public)
        logging.info('CRIADO TIPOS DE PRECO PARA O ESCRITORIO {}'.format(office.legal_name))
    PolicyPrice.objects.bulk_create(policys_price)


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0027_udapte_cost_center'),
    ]

    operations = [
        migrations.RunPython(create_default_policy),
    ]
