# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0028_policyprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepricetable',
            name='policy_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_prices', to='financial.PolicyPrice', verbose_name='Política de preços'),
        ),
    ]
