# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0031_auto_20181212_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyprice',
            options={'verbose_name': 'Tipo de Preço', 'verbose_name_plural': 'Tipos de Preço'},
        ),
    ]
