# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0035_auto_20181213_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyprice',
            name='category',
            field=models.CharField(choices=[('DEFAULT', 'Padrão'), ('PUBLIC', 'Público'), ('NETWORK', 'Rede')], max_length=255, verbose_name='Categoria'),
        ),
    ]
