# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 12:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20171207_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserByChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userbychat_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Chat', verbose_name='chat')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userbychat_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_by_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
