# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userbychat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbychat',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='chat.Chat', verbose_name='chat'),
        ),
    ]
