# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20171222_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(default='OS', max_length=100),
            preserve_default=False,
        ),
    ]
