# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_unreadmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='back_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
