# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chat_back_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-alter_date']},
        ),
    ]
