# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20180221_0933'),
        ('chat', '0009_auto_20180102_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='offices',
            field=models.ManyToManyField(null=True, related_name='chats', to='core.Office'),
        ),
    ]
