# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20180103_1908'),
        ('chat', '0009_auto_20180102_1117'),
    ]

    operations = [
    ]
