# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chat_add_related_offices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='offices',
            field=models.ManyToManyField(
                related_name='chats', to='core.Office'),
        ),
    ]
