# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_chat_company'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='unreadmessage',
            index=models.Index(fields=['user_by_message_id'], name='chat_unread_user_by_a473e6_idx'),
        ),
    ]
