# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcard',
            name='sequence',
            field=models.IntegerField(default=0, verbose_name='Sequencia'),
            preserve_default=False,
        ),
    ]
