# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboardcard_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardcard',
            options={'ordering': ['sequence']},
        ),
    ]
