# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180813_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='dashboards',
            field=models.ManyToManyField(to='dashboard.Dashboard'),
        ),
        migrations.AlterField(
            model_name='card',
            name='value',
            field=models.TextField(verbose_name='Valor'),
        ),
    ]
