# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180813_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dashboards',
            field=models.ManyToManyField(related_name='cards', to='dashboard.Dashboard'),
        ),
    ]
