# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180816_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='logo',
            field=models.ImageField(
                blank=True, null=True, upload_to='', verbose_name='Logo'),
        ),
    ]
