# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 19:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dashboard_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardDoughnutChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='Sequencia')),
                ('dashboard', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Dashboard')),
            ],
            options={
                'ordering': ['sequence'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoughnutChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('code', models.TextField(blank=True, null=True, verbose_name='Codigo')),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{"title": "string"}', null=True, verbose_name='Schema')),
                ('dashboards', models.ManyToManyField(blank=True, related_name='doughnut_charts', through='dashboard.DashboardDoughnutChart', to='dashboard.Dashboard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dashboarddoughnutchart',
            name='doughnut_chart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.DoughnutChart'),
        ),
    ]
