# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180813_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='percent',
            field=models.TextField(blank=True, null=True, verbose_name='Percentual'),
        ),
    ]
