# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_card_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='direction_value',
            field=models.TextField(blank=True, null=True, verbose_name='Direção do valor (up=subiu, down=caiu)'),
        ),
    ]
