# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180814_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='refresh',
            field=models.IntegerField(blank=True, null=True, verbose_name='Refresh por millesegundo'),
        ),
    ]
