# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_card_refresh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='refresh',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='refresh',
            field=models.IntegerField(blank=True, null=True, verbose_name='Refresh por millesegundo'),
        ),
    ]
