# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 14:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'card', app_label='dashboard')
    call_command('loaddata', 'line_chart', app_label='dashboard')
    call_command('loaddata', 'doughnut_chart', app_label='dashboard')


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180824_1306'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
