# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180814_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dashboards',
            field=models.ManyToManyField(blank=True, null=True, related_name='cards', to='dashboard.Dashboard'),
        ),
    ]
