# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 15:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20181210_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barchart',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{\n    "labels": [\n        "T\\u00cdTULOS DAS BARRAS: [JANEIRO, FEVEREIRO, MARCO]"\n    ],\n    "datasets": [\n        {\n            "label": "LABEL DO INDICADOR EX: (AUDI\\u00caNCIAS POR M\\u00caS)",\n            "data": [\n                "VALORES DO INDICADOR EX: 20, 47, 50"\n            ],\n            "backgroundColor": "COR DO BACKGROUND DE FUNDO CASO FILL = True, EX: blue",\n            "borderColor": "COR DA BORDA DA LINHA EX: blue"\n        }\n    ]\n}', null=True, verbose_name='Schema'),
        ),
        migrations.AlterField(
            model_name='linechart',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{\n    "labels": [\n        "PONTOS DA LINHA EX: [JANEIRO, FEVEREIRO, MARCO]"\n    ],\n    "datasets": [\n        {\n            "label": "LABEL DO INDICADOR EX: (AUDI\\u00caNCIAS POR M\\u00caS)",\n            "data": [\n                "VALORES DO INDICADOR EX: 20, 47, 50"\n            ],\n            "backgroundColor": "COR DO BACKGROUND DE FUNDO CASO FILL = True, EX: blue",\n            "borderColor": "COR DA BORDA DA LINHA EX: blue",\n            "fill": false\n        }\n    ]\n}', null=True, verbose_name='Schema'),
        ),
    ]
