# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 14:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_card_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{"title": "string", "subtitle": "string", "value": "string", "percent": "string", "direction": "string"}', null=True, verbose_name='Schema'),
        ),
    ]
