# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='person_lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_lawyer', to='core.Person'),
        ),
    ]
