# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 16:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lawsuit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courtdistrict',
            options={
                'verbose_name': 'Comarca',
                'verbose_name_plural': 'Comarcas'
            },
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={
                'ordering': ['-id'],
                'verbose_name': 'Pasta',
                'verbose_name_plural': 'Pastas'
            },
        ),
        migrations.AlterModelOptions(
            name='lawsuit',
            options={
                'ordering': ['-id'],
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos'
            },
        ),
        migrations.AlterModelOptions(
            name='movement',
            options={
                'ordering': ['-id'],
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentação'
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={
                'ordering': ['-id'],
                'verbose_name': 'Providência',
                'verbose_name_plural': 'Providências'
            },
        ),
        migrations.AlterModelOptions(
            name='typemovement',
            options={
                'ordering': ['-id'],
                'verbose_name': 'Tipo de Movimentação',
                'verbose_name_plural': 'Tipos de Movimentação'
            },
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='folder',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='lawsuit.Folder',
                verbose_name='Pasta'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='person_lawyer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='core.Person',
                verbose_name='Advogado'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='law_suit',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='lawsuit.LawSuit',
                verbose_name='Processo'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='legacy_code',
            field=models.CharField(
                default='',
                max_length=255,
                unique=True,
                verbose_name='Código Legado'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='person_court',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='movement_court',
                to='core.Person',
                verbose_name='Tribunal'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='person_lawyer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='movement_lawyer',
                to='core.Person',
                verbose_name='Advogado'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='type_movement',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='lawsuit.TypeMovement',
                verbose_name='Tipo de Movimentação'),
        ),
        migrations.AlterField(
            model_name='task',
            name='legacy_code',
            field=models.CharField(
                default='',
                max_length=255,
                unique=True,
                verbose_name='Código Legado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='movement',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='lawsuit.Movement',
                verbose_name='Movimentação'),
        ),
        migrations.AlterField(
            model_name='task',
            name='person',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='core.Person',
                verbose_name='Correspondente'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type_movement',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='lawsuit.TypeMovement',
                verbose_name='Tipo de Movimentação'),
        ),
        migrations.AlterField(
            model_name='typemovement',
            name='legacy_code',
            field=models.CharField(
                default='',
                max_length=255,
                unique=True,
                verbose_name='Código legado'),
        ),
        migrations.AlterField(
            model_name='typemovement',
            name='name',
            field=models.CharField(
                default='', max_length=255, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='typemovement',
            name='uses_wo',
            field=models.BooleanField(
                default=False, verbose_name='Utiliza ordem de serviço?'),
        ),
    ]
