# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0002_auto_20170511_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typemovement',
            name='legacy_code',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='typemovement',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='typemovement',
            name='uses_wo',
            field=models.BooleanField(default=True),
        ),
    ]
