# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lawsuit', '0002_auto_20170526_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='alter_user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='task',
            name='person',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type_movement',
        ),
        migrations.DeleteModel(name='Task', ),
    ]
