# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0003_auto_20170511_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typemovement',
            name='uses_wo',
            field=models.BooleanField(default=False),
        ),
    ]
