# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 17:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20170526_1648'),
        ('lawsuit', '0003_auto_20170529_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawSuitInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('alter_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('law_suit_number', models.CharField(max_length=255, unique=True, verbose_name='Número do Processo')),
                ('legacy_code', models.CharField(max_length=255, unique=True, verbose_name='Código Legado')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                 related_name='lawsuitinstance_alter_user',
                                                 to=settings.AUTH_USER_MODEL)),
                ('court_district',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawsuit.CourtDistrict',
                                   verbose_name='Comarca')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                  related_name='lawsuitinstance_create_user',
                                                  to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawsuit.Instance',
                                               verbose_name='Instância')),
                ('law_suit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawsuit.LawSuit',
                                               verbose_name='Processo')),
                ('person_court',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lawsuitinstance_court',
                                   to='core.Person', verbose_name='Tribunal')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'Instância do Processo',
                'verbose_name_plural': 'Instâncias dos Processos',
            },
        ),
        migrations.RemoveField(
            model_name='movement',
            name='law_suit',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='person_court',
        ),
        migrations.AlterField(
            model_name='movement',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='Data da Movimentação'),
        ),
        migrations.AddField(
            model_name='movement',
            name='law_suit_instance',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT,
                                    to='lawsuit.LawSuitInstance', verbose_name='Instância do Processo'),
        ),
    ]
