# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0003_auto_20170529_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instance',
            options={'ordering': ['-id'], 'verbose_name': 'Instância', 'verbose_name_plural': 'Instâncias'},
        ),
        migrations.AlterField(
            model_name='instance',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Nome'),
        ),
    ]
