# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0004_instance'),
        ('lawsuit', '0004_auto_20170513_1139'),
    ]

    operations = [
    ]
