# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0005_merge_20170515_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typemovement',
            options={'ordering': ['-id']},
        ),
    ]
