# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0006_merge_20170607_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtdistrict',
            name='active',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='active',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='active',
        ),
        migrations.RemoveField(
            model_name='lawsuit',
            name='active',
        ),
        migrations.RemoveField(
            model_name='lawsuitinstance',
            name='active',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='active',
        ),
        migrations.RemoveField(
            model_name='typemovement',
            name='active',
        ),
        migrations.AddField(
            model_name='courtdistrict',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='instance',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='lawsuitinstance',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='movement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='typemovement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='law_suit_instance',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='lawsuit.LawSuitInstance',
                verbose_name='Instância do Processo'),
        ),
    ]
