# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0010_auto_20170612_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typetask',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tipo de Serviço'),
        ),
    ]
