# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0011_merge_20170613_1405'),
        ('lawsuit', '0011_auto_20170612_1610'),
    ]

    operations = []
