# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20170622_1615'),
        ('lawsuit', '0012_merge_20170613_1415'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courtdistrict',
            unique_together=set([('state', 'name')]),
        ),
    ]
