# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0013_auto_20170622_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtdistrict',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
