# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lawsuit', '0014_auto_20170622_1704'),
        ('lawsuit', '0013_auto_20170622_1000'),
    ]

    operations = [
    ]
