# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0015_merge_20170623_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typetask',
            name='alter_user',
        ),
        migrations.RemoveField(
            model_name='typetask',
            name='create_user',
        ),
        migrations.DeleteModel(
            name='TypeTask',
        ),
    ]
