# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lawsuit', '0015_merge_20170625_2227'),
        ('lawsuit', '0015_merge_20170626_1525'),
    ]

    operations = [
    ]
