# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lawsuit', '0020_auto_20170627_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtdivision',
            name='system_prefix',
            field=models.CharField(choices=[('ADVWIN', '0')], max_length=255, null=True,
                                   verbose_name='Prefixo do Sistema'),
        ),
        migrations.AddField(
            model_name='folder',
            name='system_prefix',
            field=models.CharField(choices=[('ADVWIN', '0')], max_length=255, null=True,
                                   verbose_name='Prefixo do Sistema'),
        ),
        migrations.AddField(
            model_name='lawsuitinstance',
            name='system_prefix',
            field=models.CharField(choices=[('ADVWIN', '0')], max_length=255, null=True,
                                   verbose_name='Prefixo do Sistema'),
        ),
        migrations.AddField(
            model_name='movement',
            name='system_prefix',
            field=models.CharField(choices=[('ADVWIN', '0')], max_length=255, null=True,
                                   verbose_name='Prefixo do Sistema'),
        ),
        migrations.AddField(
            model_name='typemovement',
            name='system_prefix',
            field=models.CharField(choices=[('ADVWIN', '0')], max_length=255, null=True,
                                   verbose_name='Prefixo do Sistema'),
        ),
        migrations.AddField(
            model_name='typetask',
            name='system_prefix',
            field=models.CharField(choices=[('ADVWIN', '0')], max_length=255, null=True,
                                   verbose_name='Prefixo do Sistema'),
        ),
    ]
