# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lawsuit', '0022_auto_20170627_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtdivision',
            name='system_prefix',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='system_prefix',
        ),
        migrations.RemoveField(
            model_name='lawsuitinstance',
            name='system_prefix',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='system_prefix',
        ),
        migrations.RemoveField(
            model_name='typemovement',
            name='system_prefix',
        ),
        migrations.RemoveField(
            model_name='typetask',
            name='system_prefix',
        ),
    ]
