# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lawsuit', '0029_auto_20170705_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='legacy_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código legado'),
        ),
        migrations.AddField(
            model_name='instance',
            name='system_prefix',
            field=models.CharField(blank=True, choices=[('Advwin', 'Advwin')], max_length=255, null=True,
                                   verbose_name='Prefixo do sistema'),
        ),
    ]
