# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0030_auto_20170706_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movement',
            options={'ordering': ['-id'], 'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
    ]
