# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0031_auto_20170707_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuit',
            name='is_current_instance',
            field=models.BooleanField(
                default=False, verbose_name='Instância Atual'),
        ),
    ]
