# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import lawsuit.models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0032_lawsuit_is_current_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder_number',
            field=models.IntegerField(default=lawsuit.models.Folder.increment, unique=True, verbose_name='Número da Pasta'),
        ),
    ]
