# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0033_auto_20170906_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder_number',
            field=models.IntegerField(default=0, verbose_name='Número da Pasta'),
        ),
    ]
