# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0034_folder_folder_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='deadline',
        ),
    ]
