# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0035_remove_movement_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='person_lawyer',
        ),
    ]
