# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0036_remove_movement_person_lawyer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courtdistrict',
            options={'ordering': ('name',), 'verbose_name': 'Comarca', 'verbose_name_plural': 'Comarcas'},
        ),
    ]
