# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20171011_1632'),
        ('lawsuit', '0037_auto_20171004_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('person_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     serialize=False,
                     to='core.Person')),
                ('court_district',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.PROTECT,
                     to='lawsuit.CourtDistrict',
                     verbose_name='Comarca')),
            ],
            options={
                'db_table': 'organ',
                'verbose_name': 'Órgao',
                'verbose_name_plural': 'Órgãos',
            },
            bases=('core.person', ),
        ),
        migrations.RemoveField(
            model_name='lawsuit',
            name='person_court',
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='organ',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='organs',
                to='lawsuit.Organ',
                verbose_name='Tribunal'),
        ),
    ]
