# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        ('lawsuit', '0038_auto_20171011_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='cost_center',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='financial.CostCenter',
                verbose_name='Centro de custo'),
        ),
    ]
