# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0040_lawsuit_opposing_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='folders_movement', to='lawsuit.Folder', verbose_name='Pasta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movement',
            name='law_suit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='law_suits', to='lawsuit.LawSuit', verbose_name='Processo'),
        ),
    ]
