# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0041_auto_20171221_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawsuit',
            name='opposing_party',
            field=models.TextField(
                blank=True, null=True, verbose_name='Parte adversa'),
        ),
    ]
