# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0045_auto_20180209_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawsuit',
            name='organ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organs', to='lawsuit.Organ', verbose_name='Órgão'),
        ),
    ]
