# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0046_auto_20180525_1700'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lawsuit',
            unique_together=set([]),
        ),
    ]
