# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0048_auto_20180829_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_default',
            field=models.BooleanField(
                default=False, verbose_name='Pasta padrão para importação'),
        ),
        migrations.AddField(
            model_name='typemovement',
            name='is_default',
            field=models.BooleanField(
                default=False,
                verbose_name='Movimentação padrão para importação'),
        ),
    ]
