# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0052_auto_20181001_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawsuit',
            name='performance_place',
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='court_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='court_districts', to='lawsuit.CourtDistrict', verbose_name='Comarca'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='lawsuit.Instance', verbose_name='Instância'),
        ),
    ]
