# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='id_person_asked_by',
            new_name='person_asked_by',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='id_person_executed_by',
            new_name='person_executed_by',
        ),
    ]
