# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20170530_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='active',
        ),
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
