# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0003_auto_20170607_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='second_deadline_date',
            new_name='final_deadline_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='first_deadline_date',
            new_name='reminder_deadline_date',
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(
                blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='task',
            name='execution_date',
            field=models.DateTimeField(
                null=True, verbose_name='Data de Cumprimento'),
        ),
    ]
