# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0004_auto_20170608_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(
                blank=True, null=True, verbose_name='Descrição do serviço'),
        ),
    ]
