# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_ecm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecm',
            name='path',
            field=models.FileField(
                max_length=255, unique=True, upload_to='tasks/'),
        ),
    ]
