# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 23:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0007_auto_20170613_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecm',
            name='legacy_code',
        ),
        migrations.AlterField(
            model_name='ecm',
            name='path',
            field=models.FileField(
                max_length=255, unique=True, upload_to='GEDs/'),
        ),
        migrations.AlterField(
            model_name='ecm',
            name='task',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='task.Task'),
        ),
    ]
