# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0008_auto_20170614_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={
                'ordering': ['-alter_date'],
                'verbose_name': 'Providência',
                'verbose_name_plural': 'Providências'
            },
        ),
    ]
