# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0009_auto_20170617_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='notes',
        ),
    ]
