# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 18:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0010_remove_task_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('notes',
                 models.TextField(
                     blank=True, null=True, verbose_name='Observações')),
                ('status',
                 models.CharField(
                     choices=[('A Cumprir', 'ACCEPTED'), ('Em Aberto', 'OPEN'),
                              ('Retorno', 'RETURN'), ('Cumprida', 'DONE'),
                              ('Recusada', 'REFUSED')],
                     max_length=10)),
                ('create_user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='taskhistory_create_user',
                     to=settings.AUTH_USER_MODEL)),
                ('task',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.PROTECT,
                     to='task.Task')),
            ],
            options={
                'verbose_name': 'Histórico da Providência',
                'verbose_name_plural': 'Histórico das Providências',
            },
        ),
    ]
