# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 16:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import task.models


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0011_taskhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecm',
            name='path',
            field=models.FileField(max_length=255, unique=True, upload_to=task.models.get_dir_name),
        ),
        migrations.AlterField(
            model_name='ecm',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
    ]
