# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0012_auto_20170621_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='system_prefix',
            field=models.CharField(
                choices=[('ADVWIN', '0')],
                default='',
                max_length=255,
                verbose_name='Prefixo do Sistema'),
        ),
        migrations.AlterField(
            model_name='task',
            name='legacy_code',
            field=models.CharField(
                default='',
                max_length=255,
                unique=True,
                verbose_name='Código legado'),
        ),
    ]
