# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_auto_20170625_2227'),
        ('task', '0014_auto_20170626_1339'),
    ]

    operations = []
