# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_merge_20170626_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('A Cumprir', 'ACCEPTED'), ('Em Aberto', 'OPEN'), ('Retorno', 'RETURN'), ('Cumprida', 'DONE'), ('Recusada', 'REFUSED')], default='-', max_length=30, null=True, verbose_name='Status'),
        ),
    ]
