# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0017_auto_20170627_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='system_prefix',
            field=models.CharField(
                choices=[('ADVWIN', '0')],
                max_length=255,
                null=True,
                verbose_name='Prefixo do Sistema'),
        ),
    ]
