# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0018_auto_20170627_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='system_prefix',
        ),
    ]
