# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_task_system_prefix'),
        ('task', '0014_typetask'),
    ]

    operations = [
    ]
