# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_auto_20170630_1843'),
        ('task', '0025_auto_20170629_1610'),
    ]

    operations = [
    ]
