# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 23:20
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0027_auto_20170705_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type_movement',
        ),
        migrations.AddField(
            model_name='task',
            name='type_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='task.TypeTask',
                                    verbose_name='Tipo de Serviço'),
            preserve_default=False,
        ),
    ]
