# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0029_auto_20170725_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecm',
            name='updated',
            field=models.BooleanField(default=True),
        ),
    ]
