# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 18:23
from __future__ import unicode_literals

from django.db import migrations, models

import task.models


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0029_auto_20170725_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='typetask',
            name='survey_type',
            field=models.CharField(choices=[('Operationlicense', 'Cumprimento de Ordem de Serviço do tipo Alvará'),
                                            ('Courthearing', 'Cumprimento de Ordem de Serviço do tipo Audiência'),
                                            ('Diligence', 'Cumprimento de Ordem de Serviço do tipo Diligência'),
                                            ('Protocol', 'Cumprimento de Ordem de Serviço do tipo Protocolo'),
                                            ('Blank', '')], default=task.models.SurveyType(''), max_length=100,
                                   verbose_name='Tipo de Formulário'),
        ),
    ]
