# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0030_ecm_updated'),
        ('task', '0031_auto_20170728_1520'),
    ]

    operations = []
