# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 13:54
from __future__ import unicode_literals

from django.db import migrations, models

import task.models


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0033_auto_20170801_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(
                choices=[('A Cumprir', 'Accepted'), ('Em Aberto', 'Open'), ('Retorno', 'Return'), ('Cumprida', 'Done'),
                         ('Recusada', 'Refused'), ('Glosada', 'Blockedpayment'), ('Finalizada', 'Finished'),
                         ('Inválida', 'Invalid')], default=task.models.TaskStatus('Em Aberto'), max_length=30,
                verbose_name=''),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='status',
            field=models.CharField(
                choices=[('A Cumprir', 'ACCEPTED'), ('Em Aberto', 'OPEN'), ('Retorno', 'RETURN'), ('Cumprida', 'DONE'),
                         ('Recusada', 'REFUSED'), ('Glosada', 'BLOCKEDPAYMENT'), ('Finalizada', 'FINISHED'),
                         ('Inválida', 'INVALID')], max_length=10),
        ),
    ]
