# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0034_auto_20170801_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='validated_date',
        ),
        migrations.AddField(
            model_name='task',
            name='finished_date',
            field=models.DateTimeField(
                null=True, verbose_name='Data de Finalização'),
        ),
    ]
