# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0036_auto_20170802_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='blocked_payment_date',
            field=models.DateTimeField(null=True, verbose_name='Data da Glosa'),
        ),
    ]
