# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20170802_1421'),
        ('task', '0037_auto_20170802_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='person_distributed_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='core.Person',
                verbose_name='Service'),
        ),
    ]
