# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0038_task_person_distributed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecm',
            name='alter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecm_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por'),
        ),
        migrations.AlterField(
            model_name='ecm',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecm_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='task',
            name='alter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taskhistory_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='typetask',
            name='alter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='typetask_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por'),
        ),
        migrations.AlterField(
            model_name='typetask',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='typetask_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
