# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0040_dashboardviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder_deadline_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Primeiro Prazo'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
    ]
