# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0043_remove_task_reminder_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='final_deadline_date',
            field=models.DateTimeField(null=True, verbose_name='Prazo'),
        ),
    ]
