# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0044_auto_20171004_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Número da Providência'),
        ),
    ]
