# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-22 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0048_dashboardviewmodel_task_number'),
    ]

    sql_1 = """
        DELETE FROM auth_group_permissions AS GP USING auth_permission AS P
        WHERE GP.permission_id = P.id AND
        P.codename IN ('view_delegated_tasks', 'view_all_tasks', 'return_all_tasks', 'validate_all_tasks',
         'view_requested_tasks', 'block_payment_tasks', 'crud_system')
        """

    sql_2 = """
        DELETE FROM auth_permission WHERE codename IN ('view_delegated_tasks', 'view_all_tasks', 'return_all_tasks',
        'validate_all_tasks', 'view_requested_tasks', 'block_payment_tasks', 'crud_system')                                     
                                                          
        """

    operations = [migrations.RunSQL(sql_1), migrations.RunSQL(sql_2)]

    operations.append(migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-alter_date'], 'permissions': (('view_delegated_tasks', 'Can view tasks delegated to the user'), ('view_all_tasks', 'Can view all tasks'), ('return_all_tasks', 'Can return tasks'), ('validate_all_tasks', 'Can validade tasks'), ('view_requested_tasks', 'Can view tasks requested by the user'), ('block_payment_tasks', 'Can block tasks payment'), ('crud_system', 'Can access general data screens')), 'verbose_name': 'Providência', 'verbose_name_plural': 'Providências'},
        ))
    operations.append(migrations.AlterModelOptions(
            name='typetask',
            options={'ordering': ('name',), 'verbose_name': 'Tipo de Serviço', 'verbose_name_plural': 'Tipos de Serviço'},
        )
    )
