# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0050_auto_20171121_1651'),
    ]

    operations = [
    ]
