# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20171207_1509'),
        ('task', '0051_auto_20171206_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.Chat', verbose_name='Chat'),
            preserve_default=False,
        ),
    ]
