# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0051_merge_20171219_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-alter_date'], 'permissions': [('view_delegated_tasks', 'Can view tasks delegated to the user'), ('view_all_tasks', 'Can view all tasks'), ('return_all_tasks', 'Can return tasks'), ('validate_all_tasks', 'Can validade tasks'), ('view_requested_tasks', 'Can view tasks requested by the user'), ('block_payment_tasks', 'Can block tasks payment'), ('can_access_general_data', 'Can access general data screens'), ('view_distributed_tasks', 'Can view tasks distributed by the user')], 'verbose_name': 'Providência', 'verbose_name_plural': 'Providências'},
        ),
        migrations.AlterField(
            model_name='task',
            name='person_distributed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Person', verbose_name='Contratante'),
        ),
    ]
