# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_unreadmessage'),
        ('task', '0051_auto_20171206_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Chat', verbose_name='Chat'),
        ),
    ]
