# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0052_task_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Chat', verbose_name='Chat'),
        ),
    ]
