# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0052_auto_20171219_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(
                choices=[('A Cumprir', 'Accepted'), ('Em Aberto', 'Open'),
                         ('Retorno', 'Return'), ('Cumprida', 'Done'),
                         ('Recusada', 'Refused'), ('Glosada',
                                                   'Blockedpayment'),
                         ('Finalizada', 'Finished'), ('Inválida', 'Invalid'),
                         ('Erro no sistema de origem', 'Error')],
                default=task.models.TaskStatus('Em Aberto'),
                max_length=30,
                verbose_name=''),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='status',
            field=models.CharField(
                choices=[('A Cumprir', 'ACCEPTED'), ('Em Aberto', 'OPEN'),
                         ('Retorno', 'RETURN'), ('Cumprida', 'DONE'),
                         ('Recusada', 'REFUSED'), ('Glosada',
                                                   'BLOCKEDPAYMENT'),
                         ('Finalizada', 'FINISHED'), ('Inválida', 'INVALID'),
                         ('Erro no sistema de origem', 'ERROR')],
                max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='chat',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='chat.Chat',
                verbose_name='Chat'),
        ),
    ]
