# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0052_auto_20171207_1746'),
        ('task', '0054_auto_20171221_1059'),
    ]

    operations = [
    ]
