# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0057_auto_20180104_1742'),
        ('task', '0057_dashboardviewmodel'),
    ]

    operations = [
    ]
