# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0057_auto_20180104_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='status',
            field=models.CharField(
                choices=[('Solicitada', 'REQUESTED'),
                         ('Aceita pelo Service', 'ACCEPTED_SERVICE'),
                         ('Em Aberto', 'OPEN'), ('A Cumprir', 'ACCEPTED'),
                         ('Cumprida', 'DONE'), ('Retorno', 'RETURN'),
                         ('Finalizada', 'FINISHED'),
                         ('Recusada pelo Service', 'REFUSED_SERVICE'),
                         ('Recusada', 'REFUSED'), ('Glosada',
                                                   'BLOCKEDPAYMENT'),
                         ('Inválida', 'INVALID'),
                         ('Erro no sistema de origem', 'ERROR')],
                max_length=30),
        ),
    ]
