# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0058_dashboardviewmodel_office_id'),
        ('task', '0057_merge_20180108_1756'),
    ]

    operations = [
    ]
