# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0058_auto_20180112_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='delegation_date',
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name='Data de Delegação'),
        ),
    ]
