# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0055_auto_20180107_2144'),
        ('task', '0058_merge_20180109_1749'),
    ]

    operations = [
    ]
