# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0059_auto_20180117_0944'),
        ('task', '0059_merge_20180117_1118'),
    ]

    operations = [
    ]
