# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def get_default_office(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    admin = User.objects.filter(username='admin').first()
    if admin:
        Office = apps.get_model('core', 'Office')
        default_office = Office.objects.get(create_user=admin,
                                            cpf_cnpj='03.482.042/0001-02',
                                            name='Marcelo Tostes Advogados Associados',
                                            legal_name='Marcelo Tostes Advogados Associados')
        Task = apps.get_model('task', 'task')
        for record in Task.objects.all():
            record.office_id = default_office.id
            record.save()

        TypeTask = apps.get_model('task', 'typetask')
        for record in TypeTask.objects.all():
            record.office_id = default_office.id
            record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20180221_0933'),
        ('task', '0059_auto_20180117_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    blank=True, null=True,
                                    related_name='task_office', to='core.Office', verbose_name='Escritório'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typetask',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    blank=True, null=True,
                                    related_name='typetask_office', to='core.Office', verbose_name='Escritório'),
            preserve_default=False,
        ),
        migrations.RunPython(get_default_office),
        migrations.AlterField(
            model_name='task',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    blank=False, null=False,
                                    related_name='task_office', to='core.Office', verbose_name='Escritório'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typetask',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    blank=False, null=False,
                                    related_name='typetask_office', to='core.Office', verbose_name='Escritório'),
            preserve_default=False,
        ),
    ]
