# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 16:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0059_auto_20180117_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='auth_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                       to=settings.AUTH_USER_MODEL, verbose_name='Usuário do sistema'),
        ),
        migrations.AlterUniqueTogether(
            name='filter',
            unique_together=set([('create_user', 'name')]),
        ),
        migrations.RemoveField(
            model_name='filter',
            name='auth_user',
        ),
        migrations.AlterField(
            model_name='filter',
            name='query',
            field=models.BinaryField(blank=True, null=True, verbose_name='query'),
        ),
    ]
