# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from survey.models import get_legacy_type_map


def populate_surveys(apps, schema_editor):
    Survey = apps.get_model('survey', 'Survey')
    TypeTask = apps.get_model('task', 'TypeTask')

    survey_map = get_legacy_type_map()
    for type_task in TypeTask.objects.all():
        if not type_task.survey_type:
            continue

        survey_id = survey_map.get(type_task.survey_type)
        if survey_id:
            type_task.survey = Survey.objects.get(id=survey_id)
            type_task.save()


def remove_surveys(apps, schema_editor):
    TypeTask = apps.get_model('task', 'TypeTask')
    TypeTask.objects.all().update(survey=None)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_auto_20171228_1808'),
        ('task', '0059_auto_20180117_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='typetask',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.RunPython(populate_surveys, remove_surveys),
        migrations.RemoveField(
            model_name='typetask',
            name='survey_type',
        ),
        migrations.AlterField(
            model_name='filter',
            name='auth_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                       to=settings.AUTH_USER_MODEL, verbose_name='Usuário do sistema'),
        ),
        migrations.AlterUniqueTogether(
            name='filter',
            unique_together=set([('create_user', 'name')]),
        ),
        migrations.RemoveField(
            model_name='filter',
            name='auth_user',
        ),
        migrations.AlterField(
            model_name='filter',
            name='query',
            field=models.BinaryField(blank=True, null=True, verbose_name='query'),
        ),
    ]
