# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from survey.models import get_legacy_type_map


def populate_surveys(apps, schema_editor):
    Survey = apps.get_model('survey', 'Survey')
    TypeTask = apps.get_model('task', 'TypeTask')

    survey_map = get_legacy_type_map()
    for type_task in TypeTask.objects.all():
        if not type_task.survey_type:
            continue

        survey_id = survey_map.get(type_task.survey_type)
        if survey_id:
            type_task.survey = Survey.objects.get(id=survey_id)
            type_task.save()


def remove_surveys(apps, schema_editor):
    TypeTask = apps.get_model('task', 'TypeTask')
    TypeTask.objects.all().update(survey=None)


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20171228_1808'),
        ('task', '0059_dashboardviewmodel_office_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='typetask',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.RunPython(populate_surveys, remove_surveys),
        migrations.RemoveField(
            model_name='typetask',
            name='survey_type',
        ),
        migrations.AlterField(
            model_name='typetask',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey',
                                    verbose_name='Tipo de Formulário'),
        ),
    ]
