# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 01:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0059_auto_20180117_0944'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filter',
            unique_together=set([('create_user', 'name')]),
        ),
    ]
