# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0062_auto_20180119_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typetask',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey', verbose_name='Tipo de Formulário'),
            preserve_default=False,
        ),
    ]
