# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20180119_1226'),
        ('task', '0062_auto_20180123_1423'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('office', 'task_number')]),
        ),
    ]
