# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0063_dashboardviewmodel_office_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typetask',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey', verbose_name='Tipo de Formulário'),
        ),
    ]
