# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20180119_1226'),
        ('task', '0063_auto_20180126_1053'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('task_number', 'office')]),
        ),
    ]
