# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0064_auto_20180201_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='delegation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Delegação'),
        ),
        migrations.AlterField(
            model_name='task',
            name='final_deadline_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Prazo'),
        ),
    ]
