# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20180119_1226'),
        ('task', '0065_typetask_survey'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('task_number', 'office')]),
        ),
    ]
