# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0066_auto_20180129_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_number',
            field=models.PositiveIntegerField(verbose_name='Número da Providência'),
        ),
    ]
