# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0066_remove_task_office_executed_by'),
        ('task', '0060_typetask_survey'),
    ]

    operations = [
    ]
