# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20180119_1226'),
        ('task', '0067_auto_20180129_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='office_executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_executed_by', to='core.Office', verbose_name='Office correspondente'),
        ),
    ]
