# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0068_task_office_executed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='office_executed_by',
        ),
    ]
