# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20180208_1532'),
        ('task', '0069_remove_task_office_executed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typetask',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tipo de Serviço'),
        ),
        migrations.AlterUniqueTogether(
            name='typetask',
            unique_together=set([('office', 'name')]),
        ),
    ]
