# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0070_auto_20180208_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecm',
            name='path',
            field=models.FileField(max_length=255, upload_to=task.models.get_dir_name),
        ),
    ]
