# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import task.models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0072_auto_20180214_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='delegation_date',
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                verbose_name='Data de Delegação'),
        ),
        migrations.AlterField(
            model_name='task',
            name='delegation_date',
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name='Data de Delegação'),
        ),
    ]
