# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-08 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0073_delegation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='final_deadline_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Prazo Fatal'),
        ),
    ]
