# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0076_auto_20180413_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='billing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='receipt_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
