# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0077_taskfeedback'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='typetask',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='typetask',
            name='office',
        ),
    ]
