# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0077_auto_20180508_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Nota')),
                ('comment', models.TextField(null=True, verbose_name='Comentário')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taskfeedback_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='OS')),
            ],
        ),
    ]
