# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0079_auto_20180508_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='typetask',
            name='simple_service',
            field=models.BooleanField(default=False, verbose_name='Serviço simples'),
        ),
    ]
