# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0080_typetask_simple_service_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='person_asked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_asked_by', to='core.Person', verbose_name='Solicitante'),
        ),
    ]
