# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import task.models
import os


def get_exhibition_name(apps, schema_editor):
    Ecm = apps.get_model('task', 'Ecm')
    for ecm in Ecm.objects.all():
        ecm.exhibition_name = os.path.basename(ecm.path.name).replace(' ', '_')
        ecm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0083_dashboardviewmodel_parent_task_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecm',
            name='exhibition_name',
            field=models.CharField(blank=True, null=True, max_length=255, verbose_name='Nome de Exibição'),
        ),
        migrations.RunPython(get_exhibition_name),
        migrations.AlterField(
            model_name='ecm',
            name='exhibition_name',
            field=models.CharField(blank=False, null=False, max_length=255, verbose_name='Nome de Exibição'),
        ),
    ]
