# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0086_dashboardviewmodel_parent_task_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskgeolocation',
            options={
                'ordering': ('task', 'date'),
                'verbose_name': 'Geolocalização da Providência',
                'verbose_name_plural': 'Geolocalização das Providências'
            },
        ),
    ]
