# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0087_auto_20180828_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
