# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-10 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0087_auto_20180828_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='typetask',
            name='is_audience',
            field=models.BooleanField(default=False, verbose_name='É audiência'),
        ),
    ]
