# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 19:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0088_typetask_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTaskMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tipo de Serviço')),
                ('characteristics', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Características disponíveis')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço Principal',
                'verbose_name_plural': 'Tipos de Serviço Principais',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='typetask',
            name='simple_service',
        ),
        migrations.AddField(
            model_name='typetask',
            name='characteristics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Características disponíveis'),
        ),
        migrations.AddField(
            model_name='typetask',
            name='type_task_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.TypeTaskMain', verbose_name='Tipo de Serviço Principal'),
        ),
    ]
