# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-13 16:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0089_dashboard_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='survey_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Respotas do Formulário'),
        ),
    ]
