# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_office_use_service'),
        ('task', '0090_task_company_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='typetask',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='typetask_office', to='core.Office', verbose_name='Escritório'),
            preserve_default=False,
        ),
    ]
