# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_customsettings'),
        ('task', '0090_taskautomation'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskautomation',
            name='custtom_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_automations', to='core.CustomSettings'),
            preserve_default=False,
        ),
    ]
