# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0097_auto_20180903_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='tasksettings',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='tasksettings',
            name='workflows',
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='task_settings',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='task.TaskSettings'),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='workflow',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='task.TaskWorkflow'),
        ),
        migrations.AddField(
            model_name='taskworkflow',
            name='settings',
            field=models.ManyToManyField(related_name='workflows', through='task.WorkflowTask', to='task.TaskSettings'),
        ),
    ]
