# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0098_auto_20180905_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskworkflow',
            name='custtom_settings',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='task_workflows',
                to='core.CustomSettings'),
        ),
    ]
