# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import task.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0099_auto_20180903_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskShowStatus',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('create_date',
                 models.DateTimeField(
                     auto_now_add=True, verbose_name='Criado em')),
                ('alter_date',
                 models.DateTimeField(
                     auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active',
                 models.BooleanField(default=True, verbose_name='Ativo')),
                ('status_to_show',
                 models.CharField(
                     choices=[('Solicitada', 'Requested'),
                              ('Aceita pelo Service', 'Accepted_Service'),
                              ('Em Aberto', 'Open'), ('A Cumprir', 'Accepted'),
                              ('Cumprida', 'Done'), ('Retorno', 'Return'),
                              ('Finalizada', 'Finished'),
                              ('Recusada pelo Service', 'Refused_Service'),
                              ('Recusada', 'Refused'),
                              ('Glosada', 'Blockedpayment'),
                              ('Inválida', 'Invalid'),
                              ('Erro no sistema de origem', 'Error')],
                     default=task.models.TaskStatus('Solicitada'),
                     max_length=30,
                     verbose_name='Mostrar status')),
                ('alter_user',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='taskshowstatus_alter_user',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Alterado por')),
                ('create_user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='taskshowstatus_create_user',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Criado por')),
                ('custtom_settings',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='task_status_show',
                     to='core.CustomSettings')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='taskworkflow',
            name='task_from',
            field=models.CharField(
                choices=[('Solicitada', 'Requested'),
                         ('Aceita pelo Service', 'Accepted_Service'),
                         ('Em Aberto', 'Open'), ('A Cumprir', 'Accepted'),
                         ('Cumprida', 'Done'), ('Retorno', 'Return'),
                         ('Finalizada', 'Finished'),
                         ('Recusada pelo Service', 'Refused_Service'),
                         ('Recusada', 'Refused'), ('Glosada',
                                                   'Blockedpayment'),
                         ('Inválida', 'Invalid'),
                         ('Erro no sistema de origem', 'Error')],
                default=task.models.TaskStatus('Solicitada'),
                max_length=30,
                verbose_name='Do status'),
        ),
        migrations.AlterField(
            model_name='taskworkflow',
            name='task_to',
            field=models.CharField(
                choices=[('Solicitada', 'Requested'),
                         ('Aceita pelo Service', 'Accepted_Service'),
                         ('Em Aberto', 'Open'), ('A Cumprir', 'Accepted'),
                         ('Cumprida', 'Done'), ('Retorno', 'Return'),
                         ('Finalizada', 'Finished'),
                         ('Recusada pelo Service', 'Refused_Service'),
                         ('Recusada', 'Refused'), ('Glosada',
                                                   'Blockedpayment'),
                         ('Inválida', 'Invalid'),
                         ('Erro no sistema de origem', 'Error')],
                default=task.models.TaskStatus('Solicitada'),
                max_length=30,
                verbose_name='Para o status'),
        ),
    ]
