# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0102_auto_20180903_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskshowstatus',
            name='task_settings',
        ),
        migrations.RemoveField(
            model_name='taskworkflow',
            name='task_settings',
        ),
        migrations.AddField(
            model_name='tasksettings',
            name='cards',
            field=models.ManyToManyField(
                related_name='settings', to='task.TaskShowStatus'),
        ),
        migrations.AddField(
            model_name='tasksettings',
            name='workflows',
            field=models.ManyToManyField(
                related_name='settings', to='task.TaskWorkflow'),
        ),
    ]
