# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_remove_customsettings_task_settings'),
        ('task', '0104_auto_20180903_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksettings',
            name='alter_user',
        ),
        migrations.RemoveField(
            model_name='tasksettings',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='workflowtask',
            name='task_settings',
        ),
        migrations.RemoveField(
            model_name='workflowtask',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='taskworkflow',
            name='settings',
        ),
        migrations.AddField(
            model_name='taskshowstatus',
            name='custtom_settings',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='task_status_show',
                to='core.CustomSettings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskworkflow',
            name='custtom_settings',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='task_workflows',
                to='core.CustomSettings'),
            preserve_default=False,
        ),
        migrations.DeleteModel(name='TaskSettings', ),
        migrations.DeleteModel(name='WorkflowTask', ),
    ]
