# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_emailtemplate'),
        ('task', '0105_auto_20180904_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskworkflow',
            name='send_mail_template',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.EmailTemplate',
                verbose_name='Template a enviar'),
        ),
    ]
