# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0106_taskworkflow_send_mail_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskworkflow',
            name='send_mail_template',
        ),
    ]
