# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0108_taskshowstatus_send_mail_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typetask',
            name='office',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='typetask_office',
                to='core.Office',
                verbose_name='Escritório'),
        ),
    ]
