# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0110_ecm_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecm',
            name='system_prefix',
            field=models.CharField(
                blank=True,
                choices=[('Advwin', 'Advwin'), ('Autojur', 'Autojur'),
                         ('eLaw', 'Elaw')],
                max_length=255,
                null=True,
                verbose_name='Prefixo do sistema'),
        ),
        migrations.AlterField(
            model_name='task',
            name='system_prefix',
            field=models.CharField(
                blank=True,
                choices=[('Advwin', 'Advwin'), ('Autojur', 'Autojur'),
                         ('eLaw', 'Elaw')],
                max_length=255,
                null=True,
                verbose_name='Prefixo do sistema'),
        ),
        migrations.AlterField(
            model_name='typetask',
            name='system_prefix',
            field=models.CharField(
                blank=True,
                choices=[('Advwin', 'Advwin'), ('Autojur', 'Autojur'),
                         ('eLaw', 'Elaw')],
                max_length=255,
                null=True,
                verbose_name='Prefixo do sistema'),
        ),
    ]
