# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0114_update_delegation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='performance_place',
            field=models.CharField(default='local de cumprimento', max_length=255, verbose_name='Local de cumprimento'),
            preserve_default=False,
        ),
    ]
