# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0117_task_person_company_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='person_company_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_to_person_representative', to='core.Person', verbose_name='Preposto'),
        ),
    ]
