# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0118_taskshowstatus_mail_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskshowstatus',
            name='mail_recipients',
            field=task.models.ChoiceArrayField(base_field=models.CharField(choices=[('NONE', 'Nenhum'), ('OFFICE', 'Escritório'), ('PERSON_ASKED_BY', 'Solicitante'), ('PERSON_EXECUTED_BY', 'Correspondente'), ('PERSON_DISTRIBUTED_BY', 'Service'), ('PARENT__OFFICE', 'Escritório contratante'), ('PARENT__PERSON_ASKED_BY', 'Solicitante do contratante'), ('PARENT__PERSON_EXECUTED_BY', 'Correspondente do contratante'), ('PARENT__PERSON_DISTRIBUTED_BY', 'Service do contratante'), ('GET_CHILD__OFFICE', 'Escritório correspondente'), ('GET_CHILD__PERSON_ASKED_BY', 'Solicitante do correspondente'), ('GET_CHILD__PERSON_EXECUTED_BY', 'Correspondente do correspondente'), ('GET_CHILD__PERSON_DISTRIBUTED_BY', 'Service do correspondente')], max_length=256, null=True, verbose_name='Destinatários do e-mail'), default=[], size=None),
        ),
    ]
