# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_person_refunds_correspondent_service'),
        ('task', '0118_dashboardviewmodel_court_district_court_division'),
    ]
    operations = [
        migrations.AddField(
            model_name='task',
            name='person_company_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.Person', verbose_name='Preposto'),
        ),
    ]
