# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 18:02
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_update_survey_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0118_auto_20181023_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSurveyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('survey_result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Respotas do Formulário')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasksurveyanswer_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasksurveyanswer_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='typetask',
            name='survey_company_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_tasks_person_company_representative', to='survey.Survey', verbose_name='Tipo de formulário do preposto'),
        ),
    ]
