# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-12 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0127_auto_20181029_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='company_representative_checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_company_representative', to='task.TaskGeolocation'),
        ),
        migrations.AddField(
            model_name='task',
            name='executed_by_checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_executed_by', to='task.TaskGeolocation'),
        ),
    ]
