# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_auto_20181213_1722'),
        ('task', '0131_historicaltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='history_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Office'),
        ),
    ]
