# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-07 19:23
from __future__ import unicode_literals

from django.db import migrations, models


def change_task_to_many_2_many(apps, schema_editor):
    TaskSurveyAnswer = apps.get_model('task', 'TaskSurveyAnswer')
    User = apps.get_model('auth', 'User')

    admin = User.objects.filter(username='admin').first()

    if admin:
        survey_answers = TaskSurveyAnswer.objects.all()
        i = 0
        total = survey_answers.count()
        for survey_answer in survey_answers:
            survey_answer.tasks.add(survey_answer.task)
            if survey_answer.task.parent:
                survey_answer.tasks.add(survey_answer.task.parent)
            survey_answer.save()
            if i % 1000 == 0:
                print('{} - {}'.format(i, total))
            i += 1


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0132_task_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksurveyanswer',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='task.Task'),
        ),
        migrations.RunPython(change_task_to_many_2_many),
        migrations.RemoveField(
            model_name='tasksurveyanswer',
            name='task',
        ),
    ]
