# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0132_historicaltask_history_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='acceptance_date',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='acceptance_service_date',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='billing_date',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='blocked_payment_date',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='company_chat',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='delegation_date',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='execution_date',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='final_deadline_date',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='finished_date',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='performance_place',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='person_asked_by',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='person_company_representative',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='person_distributed_by',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='person_executed_by',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='receipt_date',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='refused_service_date',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='requested_date',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='survey_result',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='task_number',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='type_task',
        ),
    ]
