# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0133_auto_20190121_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='task_hash',
        ),
    ]
