# -*- coding: utf-8 -*-
# Generated by Tiago Gomes on 2018-10-23 18:11
from __future__ import unicode_literals

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations, models
import django.utils.timezone
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0133_auto_20190107_1723'),
    ]

    operations = []

    sql = """
        CREATE OR REPLACE VIEW dashboard_view AS SELECT task.id,
            task.parent_id,
            task.task_number,
            task.create_date,
            task.alter_date,
            task.legacy_code,
            task.delegation_date,
            task.acceptance_date,
            task.final_deadline_date,
            task.execution_date,
            task.return_date,
            task.refused_date,
            task.alter_user_id,
            task.create_user_id,
            task.person_asked_by_id,
            task.person_company_representative_id,
            task.person_executed_by_id,
            task.movement_id,
            task.is_active,
            task.description,
            task.task_status,
            task.system_prefix,
            task.type_task_id,
            task.blocked_payment_date,
            task.finished_date,
            task.person_distributed_by_id,
            task.acceptance_service_date,
            task.refused_service_date,
            task.requested_date,
            person.name AS client,
            court_district.name AS court_district,
            court_division.name AS court_division,
            type_task.name AS type_service,
            law_suit.law_suit_number,
            task.office_id,	
            task_parent.task_number AS parent_task_number
        FROM (((((((task
             JOIN movement ON ((task.movement_id = movement.id)))
             JOIN law_suit ON ((movement.law_suit_id = law_suit.id)))
             JOIN folder ON ((law_suit.folder_id = folder.id)))
             JOIN person ON ((folder.person_customer_id = person.id)))
             LEFT JOIN court_district ON ((law_suit.court_district_id = court_district.id)))
             LEFT JOIN court_division ON ((law_suit.court_division_id = court_division.id)))
             JOIN type_task ON ((task.type_task_id = type_task.id))
             LEFT JOIN task task_parent ON (task.parent_id = task_parent.id))
    """

    operations.append(migrations.RunSQL("drop view if exists dashboard_view;"))
    operations.append(migrations.RunSQL(sql))

    operations.append(UnaccentExtension())
