# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_charge_chargeitem'),
        ('task', '0134_update_task_checkin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.Charge'),
        ),
    ]
