# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0134_remove_historicaltask_task_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='task_hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
