# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 12:53
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0127_auto_20181218_1109'),
        ('task', '0135_task_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTask',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_notes', models.TextField(blank=True, null=True)),
                ('task_status', models.CharField(choices=[('Solicitada', 'Requested'), ('Aceita pelo Service', 'Accepted_Service'), ('Em Aberto', 'Open'), ('A Cumprir', 'Accepted'), ('Cumprida', 'Done'), ('Retorno', 'Return'), ('Finalizada', 'Finished'), ('Recusada pelo Service', 'Refused_Service'), ('Recusada', 'Refused'), ('Glosada', 'Blockedpayment'), ('Inválida', 'Invalid'), ('Erro no sistema de origem', 'Error')], default=task.models.TaskStatus('Solicitada'), max_length=30, verbose_name='Status da OS')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9, verbose_name='Valor')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('alter_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('create_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('history_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Office')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Office', verbose_name='Escritório')),
                ('type_task', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='task.TypeTask', verbose_name='Tipo de Serviço')),
            ],
            options={
                'verbose_name': 'historical Providência',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
