# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0136_auto_20190125_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='price_category',
            field=models.CharField(blank=True, choices=[('DEFAULT', 'Padrão'), ('PUBLIC', 'Público'), ('NETWORK', 'Rede')], max_length=255, null=True, verbose_name='Categoria do preço'),
        ),
    ]
