# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0137_historicaltask_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='alter_date',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='legacy_code',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='system_prefix',
        ),
    ]
