# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import financial.enums


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0139_update_amount_to_pay_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rate_type_pay',
            field=models.CharField(choices=[('PERCENT', 'Percentual'), ('VALUE', 'Valor')], default=financial.enums.RateType('Percentual'), max_length=10, verbose_name='Tipo de taxa a pagar'),
        ),
        migrations.AddField(
            model_name='task',
            name='rate_type_receive',
            field=models.CharField(choices=[('PERCENT', 'Percentual'), ('VALUE', 'Valor')], default=financial.enums.RateType('Percentual'), max_length=10, verbose_name='Tipo de taxa a receber'),
        ),
    ]
