# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 14:54
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0141_historicaltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9, verbose_name='Valor a pagar'),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='amount_to_receive',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9, verbose_name='Valor a receber'),
        ),
    ]
