# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 13:46
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0143_fix_task_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='amount_delegated',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9, verbose_name='Valor delegado'),
        ),
        migrations.AddField(
            model_name='task',
            name='amount_delegated',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9, verbose_name='Valor delegado'),
        ),
    ]
