# -*- coding: utf-8 -*-
# Generated by Tiago Gomes on 2018-10-23 18:11
from __future__ import unicode_literals

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations, models
from task.queries import get_dashboard_view_model_sql


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0144_auto_20190402_1046'),
    ]

    operations = []

    sql = get_dashboard_view_model_sql()

    operations.append(migrations.RunSQL("drop view if exists dashboard_view;"))
    operations.append(migrations.RunSQL(sql))

    operations.append(UnaccentExtension())
