# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0145_dashboardviewmodel_fields_ezl1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFilterViewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('legacy_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código legado')),
                ('system_prefix', models.CharField(blank=True, choices=[('Advwin', 'Advwin'), ('Autojur', 'Autojur'), ('eLaw', 'Elaw')], max_length=255, null=True, verbose_name='Prefixo do sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('task_number', models.PositiveIntegerField(verbose_name='Número da Providência')),
                ('delegation_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Delegação')),
                ('acceptance_date', models.DateTimeField(null=True, verbose_name='Data de Aceitação')),
                ('final_deadline_date', models.DateTimeField(verbose_name='Prazo Fatal')),
                ('execution_date', models.DateTimeField(null=True, verbose_name='Data de Cumprimento')),
                ('requested_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Solicitação')),
                ('acceptance_service_date', models.DateTimeField(null=True, verbose_name='Data de Aceitação pelo Contratante')),
                ('refused_service_date', models.DateTimeField(null=True, verbose_name='Data de Recusa pelo Contratante')),
                ('return_date', models.DateTimeField(null=True, verbose_name='Data de Retorno')),
                ('refused_date', models.DateTimeField(null=True, verbose_name='Data de Recusa')),
                ('blocked_payment_date', models.DateTimeField(null=True, verbose_name='Data da Glosa')),
                ('finished_date', models.DateTimeField(null=True, verbose_name='Data de Finalização')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do serviço')),
                ('task_status', models.CharField(choices=[('Solicitada', 'Requested'), ('Aceita pelo Service', 'Accepted_Service'), ('Em Aberto', 'Open'), ('A Cumprir', 'Accepted'), ('Cumprida', 'Done'), ('Retorno', 'Return'), ('Finalizada', 'Finished'), ('Recusada pelo Service', 'Refused_Service'), ('Recusada', 'Refused'), ('Glosada', 'Blockedpayment'), ('Inválida', 'Invalid'), ('Erro no sistema de origem', 'Error')], default=task.models.TaskStatus('Solicitada'), max_length=30, verbose_name='Status da OS')),
                ('asked_by_legal_name', models.TextField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('client', models.CharField(max_length=255, null=True, verbose_name='Cliente')),
                ('court_district_name', models.TextField(blank=True, max_length=255, null=True, verbose_name='Nome da comarca')),
                ('court_division_name', models.TextField(blank=True, max_length=255, null=True, verbose_name='Nome da vara')),
                ('executed_by_legal_name', models.TextField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('law_suit_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número do Processo')),
                ('opposing_party', models.TextField(blank=True, null=True, verbose_name='Parte adversa')),
                ('origin_code', models.TextField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('parent_task_number', models.PositiveIntegerField(default=0, verbose_name='OS Original')),
                ('state_initials', models.TextField(max_length=10, verbose_name='Sigla UF')),
                ('type_task_name', models.TextField(max_length=255, verbose_name='Nome Tipo de Serviço')),
            ],
            options={
                'verbose_name': 'Filtro de providência',
                'verbose_name_plural': 'Filtros de providência',
                'db_table': 'task_filter_view',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='person_company_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_to_person_representative', to='core.Person', verbose_name='Preposto'),
        ),
    ]
