# -*- coding: utf-8 -*-
# Generated by Tiago Gomes on 2019-05-02 13:30
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F
from decimal import Decimal
import logging
LOGGER = logging.getLogger('149_fix_amount_delegated')


def fix_amount_delegated(apps, schema_editor):
    Task = apps.get_model('task', 'Task')
    task_ids = list(set(Task.objects.filter(
        parent_id__isnull=False
    ).values_list('parent_id', flat=True)))
    tasks = Task.objects.filter(
        id__in=task_ids,
        amount_delegated=Decimal('0.00')
    ).exclude(
        amount_to_pay=Decimal('0.00'))
    total_updated = tasks.update(amount_delegated=F('amount_to_pay'))
    LOGGER.info('Total OS atualizadas {}'.format(total_updated))


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0148_taskfilterviewmodel_create'),
    ]

    operations = [
        migrations.RunPython(fix_amount_delegated),
    ]
