# -*- coding: utf-8 -*-
# Generated by Tiago Gomes on 2019-05-14 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations
from advwin_models.advwin import JuridAgendaTable
from sqlalchemy import bindparam
from connections.db_connection import get_advwin_engine

import logging


LOGGER = logging.getLogger('task_migrations')


def update_finished_tasks(apps, schema_editor):
    Task = apps.get_model('task', 'Task')
    tasks = Task.objects.filter(
        task_status='Finalizada',
        finished_date__gte=datetime.date(2019, 5, 1),
        office_id=1
    )
    values_list = []
    for task in tasks:
        values_list.append({'ident': task.legacy_code, 'valor_agenda': task.amount_delegated})

    stmt = JuridAgendaTable.__table__.update()\
        .where(JuridAgendaTable.__table__.c.Ident == bindparam('ident'))\
        .values(valor_agenda=bindparam('valor_agenda'))
    result = get_advwin_engine().execute(stmt, values_list)
    LOGGER.info('Total OS atualizadas {}'.format(result.rowcount))


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0149_fix_amount_delegated'),
    ]

    operations = [
        migrations.RunPython(update_finished_tasks),
    ]
