# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-12 14:50
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0151_update_executed_by_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='survey_result',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True, verbose_name='Respotas do Formulário'),
        ),
        migrations.AlterField(
            model_name='tasksurveyanswer',
            name='survey_result',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True, verbose_name='Respotas do Formulário'),
        ),
    ]
