# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultattachmentrule',
            name='person_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defaultattachmentrule_customer', to='core.Person', verbose_name='Cliente'),
        ),
    ]
