# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecm', '0002_auto_20180126_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='exibition_name',
            field=models.CharField(default='exibition_name', max_length=255, verbose_name='Nome de Exibição'),
            preserve_default=False,
        ),
    ]
