# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20180208_1532'),
        ('ecm', '0003_attachment_exibition_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='defaultattachmentrule',
            unique_together=set([('name', 'office')]),
        ),
    ]
