# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecm', '0005_auto_20180509_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultattachmentrule',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
