# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-16 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecm', '0006_defaultattachmentrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
