# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0050_auto_20171109_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Conteúdo')),
                ('type_task', models.ManyToManyField(to='task.TypeTask', verbose_name='Tipos de OS')),
            ],
            options={
                'verbose_name': 'Pesquisa',
            },
        ),
    ]
