# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20171228_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Questionário'},
        ),
    ]
