# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_office_use_service'),
        ('survey', '0003_auto_20180209_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='survey_office', to='core.Office', verbose_name='Escritório'),
            preserve_default=False,
        ),
    ]
