# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 19:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('type', models.CharField(choices=[('BOOLEAN', 'Boleano'), ('SIMPLE_TEXT', 'Texto Simples'), ('LONG_TEXT', 'Texto'), ('FOREIGN_KEY', 'Chave estrangeira'), ('INTEGER', 'Inteiro'), ('DECIMAL', 'Decimal')], max_length=15, verbose_name='Tipo')),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{\n    "is_required": {\n        "name": "is_required",\n        "title": "Campo Obrigat\\u00f3rio",\n        "type": "BOOLEAN",\n        "options": []\n    },\n    "default_value": {\n        "name": "default_value",\n        "title": "Valor Padr\\u00e3o",\n        "type": "TEXT",\n        "options": []\n    },\n    "foreign_key_options": [\n        {\n            "model": {\n                "name": "model",\n                "title": "Tabela da chave estrangeira",\n                "type": "TEXT",\n                "options": [\n                    [\n                        "Person",\n                        "Pessoa"\n                    ]\n                ]\n            }\n        }\n    ]\n}', null=True, verbose_name='Características disponíveis')),
            ],
            options={
                'verbose_name': 'Template de configuração',
                'verbose_name_plural': 'Templates de configuração',
                'ordering': ('name', 'type'),
            },
        ),
    ]
