# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 20:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_key',
            field=models.CharField(max_length=255, unique=True, verbose_name='Chave'),
        ),
        migrations.AlterField(
            model_name='templatevalue',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{\n    "office_id": null,\n    "template_key": null,\n    "template_type": null,\n    "value": null\n}', null=True, verbose_name='Valor'),
        ),
    ]
