# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 20:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0002_auto_20190319_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='alter_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='template',
            name='alter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por'),
        ),
        migrations.AddField(
            model_name='template',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='create_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='template_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
