# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190322_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_key',
            field=models.CharField(choices=[('DEFAULT_CUSTOMER', 'Cliente padrão'), ('EMAIL_NOTIFICATION', 'E-mail de notificação'), ('USE_SERVICE', 'Equipe conferência dados'), ('USE_ETL', 'Importa dados de outros sistemas')], max_length=255, unique=True, verbose_name='Chave'),
        ),
    ]
