# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 13:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20190319_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='key_schema',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Chave'),
        ),
        migrations.AlterField(
            model_name='template',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{\n    "type": "object",\n    "title": "Par\\u00e2metros de configura\\u00e7\\u00e3o",\n    "required": [\n        "is_required"\n    ],\n    "properties": {\n        "is_required": {\n            "title": "Obrigat\\u00f3rio",\n            "type": "boolean",\n            "format": "checkbox"\n        },\n        "model": {\n            "type": "array",\n            "format": "select",\n            "title": "Tabelas de chave estrangeira",\n            "uniqueItems": true,\n            "items": {\n                "type": "object",\n                "title": "Modelo",\n                "properties": {\n                    "table": {\n                        "title": "Classe",\n                        "type": "string",\n                        "enum": [\n                            "Person"\n                        ],\n                        "default": "Person"\n                    },\n                    "extra_params": {\n                        "title": "Par\\u00e2metros extra",\n                        "type": "string",\n                        "format": "python",\n                        "options": {\n                            "ace": {\n                                "theme": "ace/theme/vibrant_ink",\n                                "tabSize": 4,\n                                "useSoftTabs": true,\n                                "wrap": true\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }\n}', null=True, verbose_name='Características disponíveis'),
        ),
    ]
