# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 13:50
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_companyuser_show_administrative_menus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0004_auto_20190320_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}', null=True, verbose_name='Respostas')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templateanswers_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templateanswers_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templateanswers_office', to='core.Office', verbose_name='Escritório')),
            ],
            options={
                'verbose_name': 'Configuração por escritório',
                'verbose_name_plural': 'Configurações por escritório',
                'ordering': ('office', 'template'),
            },
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('BOOLEAN', 'Boleano'), ('FOREIGN_KEY', 'Chave estrangeira'), ('DECIMAL', 'Decimal'), ('INTEGER', 'Inteiro'), ('LONG_TEXT', 'Texto'), ('SIMPLE_TEXT', 'Texto Simples')], max_length=15, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='templateanswers',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Template', verbose_name='Configuração'),
        ),
    ]
