# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 16:42
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0132_companyuser_show_administrative_menus'),
        ('manager', '0005_auto_20190320_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alter_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}', null=True, verbose_name='Valor')),
                ('alter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templatevalue_alter_user', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templatevalue_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templatevalue_office', to='core.Office', verbose_name='Escritório')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Template', verbose_name='Configuração')),
            ],
            options={
                'verbose_name': 'Configuração por escritório',
                'verbose_name_plural': 'Configurações por escritório',
                'ordering': ('office', 'template'),
            },
        ),
        migrations.RemoveField(
            model_name='templateanswers',
            name='alter_user',
        ),
        migrations.RemoveField(
            model_name='templateanswers',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='templateanswers',
            name='office',
        ),
        migrations.RemoveField(
            model_name='templateanswers',
            name='template',
        ),
        migrations.DeleteModel(
            name='TemplateAnswers',
        ),
    ]
