# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20190320_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatevalue',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='Valor'),
        ),
    ]
