# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_load_template_fixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_key',
            field=models.CharField(choices=[('DEFAULT_CUSTOMER', 'Cliente padrão'), ('DUPLICATE_PROCESS', 'Duplicar número de processo'), ('EMAIL_NOTIFICATION', 'E-mail de notificação'), ('USE_SERVICE', 'Equipe conferência dados'), ('USE_ETL', 'Importa dados de outros sistemas'), ('MIN_HOUR_OS', 'Limite para abertura de OS'), ('I_WORK_ALONE', 'Trabalho sozinho'), ('DEFAULT_USER', 'Usuário padrão')], max_length=255, unique=True, verbose_name='Chave'),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('BOOLEAN', 'Boleano'), ('FOREIGN_KEY', 'Chave estrangeira'), ('DECIMAL', 'Decimal'), ('INTEGER', 'Inteiro'), ('LIST', 'Lista de opções'), ('LONG_TEXT', 'Texto Longo'), ('SIMPLE_TEXT', 'Texto Simples')], max_length=15, verbose_name='Tipo'),
        ),
    ]
